### ISSUE TITLE
New mode proposal

### ISSUE THREAD

**Issue by Gimmo** [Megabyte918/MultiOgar-Edited#115]
I offer a new mode. TAX mode.

Keywords:: Anti Teaming, Anti Monsters Domination, Newcomers Friendly.

1. Cell's life time has price. Cell loose a percent of mass per time (more motion - better life).
2. Cell pay a LifePrice by emitting a food. Of course, Cell can come back and eat it. It should oscillate just to stay alive,or move collecting food. Monster max size automatically (without programming) limited by foodDistribution-lifePrice-motion  balance. 
3. Baby Cells not eatable, so newcomer has a chance to understand gameplay. Baby Cells can subsist around big Cells....to be eaten later.
4. When Cell killed or affected by virus - a part of it's mass disappears. Like a tax. It will kill teaming. (as like in petridish)

Parameters::

LifePrice %/sec
Legal Age or/and Mass 
Tax % 

Maybe someone can/want to implement this?

**Comment by Megabyte918** [comment]
@Gimmo 
1) Lag
2) Lag
3) Can be done, but mostly pointless because of the spawn protection. You wont spawn near someone that will immediately splitkill you (most of the time) anyway
4) Can be done, but why wouldn't you want to eat 100% of the mass? if your just a solo player then its kinda pointless.

**Comment by Gimmo** [comment]
@Megabyte918 
3. OK, but first part (not eatable before legal age / mass) still important for beginners. I test some games, and often was killed on very begining, just starting game, without understanding something at all. It's very disappointing.
4. In teamwork one of most popular tactics - support leader by injection(share) of mass . If it will cost - single player will have slightly more chances against croud.  Single player eating  enemy will have profit still. Command will have losts.

**Comment by Fantasy-Agario** [comment]
@Megabyte918 Sorry I had to go off c9 I will be back on tomorrow tho 🙂

**Comment by Megabyte918** [comment]
@Fantasy-Agario its alright
@Gimmo 
3. I just realized, in order for cells to ignore collision when they first spawn would cause tremendous lag. You would need to set a timeout on the eat collisions per every player spawned, and that means that all those timeouts running/piling up every time someone spawns would decrease performance by a tremendous amount. I don't think it would be a good idea especially if you have alot of players/bots/minions on your server and their constantly dying/spawning.

4. You can edit how much mass a player gets once they consume an entity by editing the `onEat` function in Cell.js.

**Comment by NameYT** [comment]
@Megabyte918 Can you give me a code for the Bot Smarter? i have 3 TB Computer and fast :)

**Comment by Megabyte918** [comment]
@NameYT that code doesn't exist, and you should be thanking @ZfsrGhS953 for making pellet mode :)

**Comment by NameYT** [comment]
@Megabyte918 I mean the calculation :)

**Comment by Gimmo** [comment]
@Megabyte918 

3. LegalAge can be Maximal Mass In This Session, not a timer.
Can we limit collisions with same algorithm as used to ignore collisions of small cells with viruses? Can it help to avoid lags?

**Comment by Megabyte918** [comment]
@Gimmo Not a good idea either:
That means that every single cell under the specified mass ignores eat collisions. Example: lets say that the specified mass is 50. That means that every cell on the server under 50 mass will ignore collision. This includes ignoring food, viruses, ejected cells, and itself (they will not collide with each other as in if the two cells were to touch, they would just go inside of each other rather than just touch edges). This means if you spawn with 50 mass, you wont be able to eat any entities or collide with your own cells, so you would never be able to grow to the point where you regain collision.

**Comment by Gimmo** [comment]
OK, I think a temporary solution can be to find an empty space and spawn new cell in it's center instead of random place. May be mini-map can be used for this?

**Comment by Megabyte918** [comment]
@Gimmo the server already does that

**Comment by Gimmo** [comment]
May be I have a bad lack - to be killed on start almost always. 
Thanks. I'll return to this later. (Have had to learn Ogar more)  :)

**Comment by Megabyte918** [comment]
Alright, I will close this for now.
