### ISSUE TITLE
ANNOUNCEMENT: Read description

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#1169]
So, I officially coded my own [website](http://multiogarcalculator.tk) <- Click that to go to it.

Ever had them annoying times when you want to change your spawnmass to something like 450, but it's complicated to find out **val * val / 100 = 450**? 
On this website, click the button, enter the mass amount you want to be the spawnmass, and press OK. It gives a number. Copy that number, paste it in the spawnmass, boom there's your wanted spawnmass!

_Trying my best to not self promote, but ya know, it makes things a lot easier_

**Comment by AlexHGaming** [comment]
Sorry it is off topic to this project, but it helps a huge bunch :-)

**Comment by AlexHGaming** [comment]
and ik the website looks shit, but x2, i rushed it.

**Comment by ZfsrGhS953** [comment]
@AlexHGaming Why do you use 000webhost? Use GitHub Pages instead, no stupid watermarks.

**Comment by FantasyIsBae** [comment]
@ZfsrGhS953 Do you still hate me for editing your comment?

**Comment by AlexHGaming** [comment]
meh

**Comment by ZfsrGhS953** [comment]
@FantasyIsBae No, because Github now displays that the comment has been edited (or did it do that always? In that case I'm stupid). But now I hate you because you somehow became a collaborator while being only 13 years old. You're still too young, you take advantage of other people doing work for you (see [here](https://github.com/Megabyte918/MultiOgar-Edited/issues/967#issuecomment-313307463)) and you don't pay attention while you moderate (see [here](https://github.com/Megabyte918/MultiOgar-Edited/issues/1140#issuecomment-315637588)).  I'm not going to get angry at Megabyte if he keeps you as collaborator. It's only my point or view: become better at being a collaborator, or let the grown men do the work.

**Comment by AlexHGaming** [comment]
Please take this arguement into dm's.
@FantasyIsBae @ZfsrGhS953

**Comment by FantasyIsBae** [comment]
@ZfsrGhS953 
No GitHub only started doing that a few months ago 😄 
I don't take advantage of people , that's the last thing I would do , as to me closing that issue , well I closed it accidentally as at the time I had to close 300+ issues because some idiot decided to spam the issues section. For the other , Bot AI was mentioned too many times , even Mega or Chewy said to logicalatomical that it would make this project become more like OgarUL. Also you're never too young to do anything , unless its illegal.  I was taken off of collaborator once or twice , but as Megabyte and Makan weren't active, I got it back. I know I'm only 13 , but I am more mature than you may think.

Anyways I'm sorry for what happened a few months back , thanks for forgiving me.

**Comment by MastaCoder** [comment]
I'm not liking where this repository is going. It's being filled with a lot of useless updates and dead just like Ogar-Unlimited. I'm going to talk to Megabyte a bit and cleanup the repo.
