### ISSUE TITLE
The history

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#1177]
In this project, always talking about not doing certain things, because VANILLA does not have them, but nevertheless have things like chat, clientBind, quite contradictory. Better to say that they do not have enough knowledge to do it, or else make an official announcement that they do not know how to do it. And the comments, like: "Do it yourself", that's what I do :), lucky. On the other hand enough programmers of the agar community, they believe the great thing, guys it is not difficult to learn languages ​​of high level, as it happens with the low level. Also I read people like AlexHGaming, who think that they are programmers in front of other children of 10-12 years who do not know anything about this, if they do not know how to implement something, better to say no. There are few "humble" people in the general agar community, in fact there are more children practically believing in software / computer engineers, and they do not know anything about physics / math, kids greetings.

I think this project should be closed

**Comment by AlexHGaming** [comment]
> Also I read people like AlexHGaming, who think that they are programmers in front of other children of 10-12 years who do not know anything about this,

1. I do not know how to code
2. I do not know how to code
3. I do not know how to code

I do not think this project should be closed because think of it, it is a free open source project. This server provides you minions, AI bots + more. Vanilla agar doesnt supply this. I don't understand why a project that has had loads of time and effort into being made into has to be close.

> Better to say that they do not have enough knowledge to do it, or else make an official announcement that they do not know how to do it. And the comments, like: "Do it yourself", that's what I do :),

Which is why, we have an issues section. Providing help for the people who need it.

> who think that they are programmers

I never said i thought about me being a programmer. I do simple javascript, such as functions and arrays i.e, not node.js and this engine & shit.

This project maybe not going the right way, but like i keep saying, **it's free**. It's open source. Better than nothing being here in the first place.

**Comment by AlexHGaming** [comment]
> front of other children of 10-12 years who do not know anything about this,

Please name some issues that people were clueless where we didnt explain to them in easy detail.

**Comment by MastaCoder** [comment]
Lets start off with vanilla. This project is no way to be exactly like vanilla, neither is it supposed to be Ogar Unlimited. I've seen the requests you've made, they've all been terrible requests to just add more stress on the server. MultiOgar is here to help you start off with a working private server, extra code? Add it yourself.

This is the issues section of a project, not a help forum to get spoon fed code. You'll be guided to lines or a way to do it, but we won't provide the direct code for you to just copy and paste. Put effort into it.

Please stop making useless requests, thanks.
