### ISSUE TITLE
how? xD

### ISSUE THREAD

**Issue by MiraMiPalo** [Megabyte918/MultiOgar-Edited#1241]
how indicate in PlayerTracker.js ._.   if this is virus, ejected, food
`if  (this.userRole == :v) this.isSpiked;`

**Comment by Agarian** [comment]
I don't understand the point of your question. The server can already distinguish players, viruses, ejected cells, and food from each other. Unless your asking for some sort of statistic that tells you mow many players, bots, minions, viruses, ejected cells, and food cells are on the map. Either way, please word your question better, for the sake of understanding.

**Comment by AlexHGaming** [comment]
Sorry, I don't know a file called "playerTrakcer"

**Comment by Agarian** [comment]
OH I see now, so you want to make food, viruses, ejected, and cells spiked? (thanks for editing the message BTW)

**Comment by Fan7asy** [comment]
@MiraMiPalo 

First you will need to put the `UserRoleEnum` variable into global focus.
In order to do this move [Line 75](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PlayerTracker.js#L75) to the top (somewhere about [here](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PlayerTracker.js#L4));

Next add the following snippet of code to the bottom of the [sendUpdate](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/PlayerTracker.js#L229) prototype function:
```JS
    if (this.userRole === UserRoleEnum.ADMIN) {
        for (var i = 0; i < this.cells.length; i++) {
            var cell = this.cells[i];
            cell.isSpiked = true;
        }
    };
```

Now if you login as the `ADMIN` role you should see the following result:

![cap](https://user-images.githubusercontent.com/21162678/30813273-e298a964-a204-11e7-90ab-868c42ee11fa.PNG)

## Please note that you can use this with any user role.

Just replace `UserRoleEnum.ADMIN` with `UserRoleEnum.<Which ever role>`

**Comment by MiraMiPalo** [comment]
@Fan7asy  Thanks! ♥

**Comment by AlexHGaming** [comment]
ok close

**Comment by MiraMiPalo** [comment]
@AlexHGaming  No! :v

**Comment by AlexHGaming** [comment]
@MiraMiPalo why not?

**Comment by AlexHGaming** [comment]
@MiraMiPalo _@Fan7asy Thanks! ♥_ <- Clearly indicated the issue must be closed.

**Comment by MiraMiPalo** [comment]
@AlexHGaming eso indica que te amo xD

**Comment by AlexHGaming** [comment]
@Fan7asy wtf

**Comment by MiraMiPalo** [comment]
que? :v

**Comment by Fan7asy** [comment]
@MiraMiPalo No problem :)

**Comment by Fan7asy** [comment]
@AlexHGaming I'm not on GitHub 24/7, i do have other things to do, hence I couldn't close the issue.

**Comment by Shair17** [comment]
@MiraMiPalo [Nel :v]

En packethandler es donde puedes enviar los paquetes
