### ISSUE TITLE
HELP WITH TAB CONTROL

### ISSUE THREAD

**Issue by Wair1o17** [Megabyte918/MultiOgar-Edited#1252]
How to control minions with TAB, I have already made configurations in the client, emit (18)
However, there are still problems, some help?

**Comment by cyclopentan** [comment]
What client you use? What will happen when you press TAB.
P.S. Don't use CAPS

**Comment by Wair1o17** [comment]
I'm using Agarplus client, hmm
I get manage to control the bot with the TAB, but there were some problems like that did not respond very well and was slow to respond.

**Comment by cyclopentan** [comment]
Are you sure, that issue is server-sided? Maybe MultiOgar-Edited doesn't support bot control feature.

Communication scheme look like this: You(Browser) -> client JS code -> WebSocket message -> server
What happens when you press TAB in Agarplus? Maybe client JS code converts your TAB to unknown for server ws-message.

Is it feature request?

**Comment by AlexHGaming** [comment]
@cyclopentan He is trying to change the button from Q to TAB, you don't need to give him the javascript knowledge lmao

**Comment by Fan7asy** [comment]
Just change the keycode from the one for Q to the one for TAB... No need for any critical changes.

**Comment by cyclopentan** [comment]
Okay :)
