### ISSUE TITLE
After Certain Number of Auto Restart Server Dont allow connection

### ISSUE THREAD

**Issue by fayizan** [Megabyte918/MultiOgar-Edited#1255]
Server Stop Accepting Connections after certain number of auto restart :|

**Comment by Agarian** [comment]
Wait, do you want this as a feature, or is that in issue you've ran into?

**Comment by ItzLevvie** [comment]
@Agarian It's a issue that he has run into.

**Comment by fayizan** [comment]
yup its an issue

**Comment by fayizan** [comment]
@ZfsrGhS953 and @cowpits Pls Halp :  |

**Comment by cowpits** [comment]
Is the server running on codeanywhere? If it is set your serverIpLimit = 0 default is 4. 
reason you do that on codeanywhere or some other VPS is because the external IP is NAT'd to an internal IP so all connections are coming from the same internal IP.

**Comment by fayizan** [comment]
nope I use a dedicated server and I didnt change the ip limit

**Comment by cowpits** [comment]
can you set your serverIpLimit to 0 
also who's your hosting company and share your site link if you want to.

**Comment by cowpits** [comment]
how many servers? and are they all set to auto restart? 
because i do auto restart and i never run into issues with people not reconnecting. I restart every 7 minutes on one server and the other every 60. 
so really check your serverIpLimit and set it to 0

**Comment by cowpits** [comment]
i tested your servers
http://agar.io/?ip=game.fzogar.xyz:4000  and http://agar.io/?ip=game.fzogar.xyz:4001 
i spawn frozen but shows me twice on leaderboard
http://agar.io/?ip=game.fzogar.xyz:5000 couldn't connect with agar client but could with mine
http://agar.io/?ip=game.fzogar.xyz:5001 was fine
http://agar.io/?ip=game1.fzogar.xyz:4000 and http://agar.io/?ip=game1.fzogar.xyz:4001 were fine but game play is sluggish
the 1st 4 servers are on this VPS IP = 195.181.243.147 
the last 2 are on this VPS IP = 128.199.76.99
What are the number of CPU Cores and RAM for each? 
Here test them on my test client here if you like http://www.tutorialscow.96.lt/tutorial/

**Comment by fayizan** [comment]
@cowpits sorry for the late reply. Those are running on 8 core and 16 gb vps and I didnt update all the servers to auto restart update.. was checking with only one server atm.
Lemme check with `serveriplimit=0` and tell you what happends  
Thanks

**Comment by fayizan** [comment]
@cowpits how to overcome the sluggish, I almost made it to match the agario vanilla setting :|

**Comment by cowpits** [comment]
That was my bad on the typo for the 5000 port. 
Anyway, 8 cores and 16g ram is enough to run 6 servers but you are sharing the Nick. Assuming you are on a 1GB connection, although you can burst to that speed you're still sharing the connection with all other VPS' in the cluster. 
I always tell people to get 1 core and 2gig ram VPS and run one server, rather than a loaded VPS and many servers. There's a lot of traffic in the game and client. Also location plays a big role as far as connection. 
Try running a couple of servers and see if it improves performance instead of running them all at once. 
I'm testing my BOTS server on a VPS 1vCPU and 2Gig ram with unmetered bandwidth. $3.49/month. Seems to be doing ok and no complaints about lag. At that price I'll get 2 more if I need to.

**Comment by fayizan** [comment]
@cowpits setting `serveriplimit=0` Worked Tysm and about the vps I will try to change next time : )
