### ISSUE TITLE
Ogar Tracker is gone :(

### ISSUE THREAD

**Issue by Hydra4dude** [Megabyte918/MultiOgar-Edited#1295]
Hello, I wanted to know what happened to the ogar tracker, which was a page with several ip's of server's privates of the multiplayer, and that I had a lot of fun playing in it, so I want to know what happened to the page?

THANK YOU!

**Comment by AlexHGaming** [comment]
Not a valid issue.

**Comment by Agarian** [comment]
Ogar Tracker has gone down, yes, though I've never seen it work with MultiOgar-Edited servers. I'm unsure why they've gone down, but they have.

**Comment by Fan7asy** [comment]
@Hydra4dude Seems like the domain has expired and with no one to put it back up, I guess its gone forever, or at least till Barbosik is back.

**Comment by ZfsrGhS953** [comment]
@Hydra4dude I'm pretty sure that @Barbosik has shut down Ogar-Tracker because he is envying us for making MultiOgar better, (or "stealing" as he said that to me for making Petridish Ogar, even though the license file is [right here](https://github.com/ZfsrGhS953/Petridish-Ogar/blob/master/Ogar/LICENSE.md)) and that he can't do the same thing on his own due to poor programming skills.

**Comment by Luka967** [comment]
LMAO when'd he say THAT

**Comment by ZfsrGhS953** [comment]
@Luka967 [Here you go.](https://github.com/Barbosik/MultiOgar/issues/109) So I removed an unnecessary copyright header because there already was a LICENSE.md file with the Apache License text, and instead of saying "Thank you for noticing, I'll remove it in MultiOgar master as well", he said this (I'm posting it here in case he gets scared and deletes that comment):

> 
ZfsrGhS953: links which consists of code with replaced copyright header is not allowed here.
You posted a link with code which violates clause 4 (c) of Apache 2 license.

You can modify and redistribute the code. But you're not allowed to remove all copyright, patent, trademark, and attribution notices from the Source form of the Work.

By distributing source code with removed copyright you make criminal offense and legislative actions can be applied to you, and it's not a joke. Please apply Apache 2 license requirements and return copyright headers back.

PS: also, your mod using very old, outdated version of MultiOgar code, a lot of optimizations is missing. And I didn't found any optimization in comparison with MultiOgar. You just added some mistaken code which cannot improve performance and a lot of checks added to onEat handler - it add lags.

>

**Comment by Luka967** [comment]
WOW.
I know that I could have fucked up big time with Ogar's quadtree (which isn't even one) but this is WAY too much copyright enforcement.

**Comment by Fan7asy** [comment]
Woah that's a little salty

**Comment by ZfsrGhS953** [comment]
@Fan7asy A little? You have quite a low sensitivity to salinity.

**Comment by Fan7asy** [comment]
Perhaps more than a little :D
