### ISSUE TITLE
How to get bots more smarter?

### ISSUE THREAD

**Issue by ThebigbossCE** [Megabyte918/MultiOgar-Edited#1298]
Hi, i have seen before that you helped some users to get more smarter minions.
But, this is not wirking with the actual Multiogar edited master version.

So, please, anyone knows how to change :
- Big bots never splits
- Little bots splitting everywere (wtf? too easy)
- And maybe add "slow teamers bots" or "splitrunning bots" or the capacity for the bots to doublesplit ;)

If this is possible, can someone helps me ?
Thanks

**Comment by AlexHGaming** [comment]
Smarter Bots lead to performance issues.

**Comment by ThebigbossCE** [comment]
Ah.. so it's impossible ?

**Comment by TopoR1** [comment]
@ThebigbossCE This Multi-Ogar is better than the agar.io server in terms of functionality, and, at the moment, it's enough. It remains only to refine the physics and look for errors. And those who want to improve it for themselves, so do it yourself, because many ideas are harmful to performance, but is it necessary?

**Comment by Agarian** [comment]
This dude has a very familiar profile image.

**Comment by MiraMiPalo** [comment]
@Agarian xD

**Comment by DeadLord1337** [comment]
duplicate over x9999
