### ISSUE TITLE
 Configuration with Mothercell

### ISSUE THREAD

**Issue by Gatoz** [Megabyte918/MultiOgar-Edited#1321]
Hello, well first this is not a problem, it's a query. I have noticed that when I enter the EXPERIMENTAL game mode, the mothercell do not produce food, I would like to know if I can modify so that they generate little or large amount of food and if the amount of mothercell can be established in the game, I hope your help. Thanks

postscript: sorry if some word is misspelled, I do not handle much English

**Comment by AlexHGaming** [comment]
@Fan7asy

**Comment by Fan7asy** [comment]
The food that the mother cells produce is limited to the maximum food amount for the server.
This is because if the quantity of cells produced increments to a value higher than the max allowed by the server, the server will lag very very much, almost till the point where it is unplayable.

If you really want to change the value you may want to change the value of `maxFood` inside the `onUpdate` function in [Mothercell.js](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/entity/MotherCell.js)

**Comment by Gatoz** [comment]
ok I understand, but not even be little food, please if you can in what line number I make the change and what should I put, explain me in detail, I do not understand much ..... on YouTube I've seen some old tutorials, where food comes out with the same multiogar, but with this version you can not? , ota consult I have created my agar.io server but I would like to record some gameplays for my channel on YouTube, it is allowed, or they can allow me or to whom I ask permission, who is the owner of multiogar, Thanks

**Comment by Agarian** [comment]
@Fan7asy He's referencing how mother cells in agar.io's experimental mode can eject food, even if the `motherMinSize` value has been reached, though the food ejection is much slower once the mother cell's size reaches that value. Here, that doesn't happen, and he (and also kind of I) want that to happen.

**Comment by Gasvash** [comment]
@Fan7asy  , it is true, it can be configured so that the mother cell produces food?, because it produces nothing in the game, as well as the gota.io client (experimental mode) that produces it

**Comment by StormCDJS** [comment]
Yo diria que me la pelan. Gracias por su atención.

**Comment by AlexHGaming** [comment]
@StormCDJS English only please bud.
