### ISSUE TITLE
Discord major outages (and some info on the agar.io client update)

### ISSUE THREAD

**Issue by Agarian** [Megabyte918/MultiOgar-Edited#1327]
Yeah, yeah this is `invalid`, but this is an issue for a lot of people here, as many use Discord. As many more of you know, Discord has had a line of major outages recently, and as of `Saturday, November 18, 2:48 PM E.S.T.`, Discord has suffered yet another outage. Just some information for those having trouble using Discord recently.

**EDIT:** Discord is now back up.

And some information on agar.io's recent update:
- There are now `DNA` points and apparently `potions`.
- The skins issue is happening on official agar servers as well, though skins just don't appear on your cell.
- Do not check the `Hide Skins` option, as it WILL crash the agar.io client.
- The update appears to have broken custom skins again, though it's likely related to the skins bug.
- Other than that, the client remains relatively unchanged.

**Comment by Gatoz** [comment]
you can find a solution
  my esteemed ?
I hope a "yes", at least there will be hopes
I am therefore submitting mass claims to miniclip to eliminate the update, this is affecting the game and also to customers

**Comment by ThebigbossCE** [comment]
Yeah this is hard :/ Moneyclip are always trying to update Agar..

**Comment by ZfsrGhS953** [comment]
@Agarian Host a Discord on your server. This isn't possible yet. But I will make it possible soon...

**Comment by Agarian** [comment]
Discord is a WEBSITE

**Comment by AlexHGaming** [comment]
@Agarian discord is also an app :weSmart:

**Comment by Agarian** [comment]
When did you become so salty all of a sudden?

**Comment by AlexHGaming** [comment]
@Agarian never?

**Comment by Luka967** [comment]
Wat do you mean by that @ZfsrGhS953

**Comment by Fan7asy** [comment]
I assume he's making a discord server implementation @Luka967

**Comment by cowpits** [comment]
Yeah the agario client skin issue started back in the last update of July 2016 if I remember correctly, where users cannot see their own skin but can see others. In this update, if you add a skin in tags <skin> everyone to the player will have the same skin as we figured in #1324. 
Miniclit screwed up somewhere, but we shouldn't be able to see the skin at all and yes checking the no skin option crashes the client. Why they're doing this is stupid in my opinion because we all run our own clients and its easy to get their skins and upload them.

**Comment by Agarian** [comment]
k

**Comment by SuperOP535** [comment]
l

**Comment by AlexHGaming** [comment]
m

**Comment by SuperOP535** [comment]
n
