### ISSUE TITLE
How to get no lag while using 700 minions? Launching the Server to 32 GB HOW?W?

### ISSUE THREAD

**Issue by NameYT** [Megabyte918/MultiOgar-Edited#167]
Help

**Comment by NameYT** [comment]
@Megabyte918

**Comment by firelightning13** [comment]
@NameYT Get better cpu

**Comment by Megabyte918** [comment]
@NameYT Performance with minions greatly depends on the starting size. For me, I was able to run 700 minions with the default starting size (32), and I had no lag. Try setting your minion's start size to lower. Also this is not an issue so I'm closing it.

**Comment by NameYT** [comment]
@Megabyte918 When i collect pellet mode then it got big and split once the server is lagging is there anyway i can run my server? 25GB

**Comment by systemroot** [comment]
you can have 32GB or 200GB ram. based on your CPU lag will be the same.
with CPU 4.0GHz overclock 4.4CPU was able to play with 1K minions for some hours without lag or slow time. 
with 5K minions for 1-2/H game is slow. 
u can see how this https://www.ovh.co.uk/dedicated_servers/details-servers-range-GAME-id-MC-32.xml dedicated server is with 5K minions https://vid.me/vHm1

if you are running a server from your pc, well this is another case because your server will eat CPU but chrome will eat CPU too so monitor your cpu and watch how much minions are you able to use.

**Comment by MastaCoder** [comment]
Remember it's not always just CPU being affected. If you're trying to load 5k bots many other things come into affect. Some to list:

- Server network speeds
- Server network latency
- Client network speeds
- Client network latency
- Client being used
- How cells are rendered in the client
- How fast the users computer can render them
- Distance from server

And more. Just because you have all these on your server, doesn't mean you're going to get 100% performance.

**Comment by NameYT** [comment]
@Megabyte918 @MastaCoder I mean how to run the server 32GB i have 1 Terabytes

**Comment by Megabyte918** [comment]
1 Terabyte of ram...

**Comment by systemroot** [comment]
i'm thinking he's taking disc as ram!

**Comment by NameYT** [comment]
@Megabyte918 Just tell me how to run it lol

**Comment by Megabyte918** [comment]
@NameYT Refer to https://github.com/Barbosik/MultiOgar/issues/351
