### ISSUE TITLE
Mass Command Enhancement!

### ISSUE THREAD

**Issue by PrinceDark9243** [Megabyte918/MultiOgar-Edited#168]
Mass Command Enhancement
Old Commad `mass [ID] [AMOUNT]`

TO NEW `mass [ID] [CMD] [AMOUNT]`

in CMD you need to put `s`=Set ,`r`=Remove ,`a`=Add (this cmd contains the commad data like removing mass adding mass setting mass)

ex: `mass 1 a 100` (Add 100 mass to 1 ID player [ALL CELLS])
ex: `mass 1 r 100` (remove 100 mass to 1 ID player [ALL CELLS])
ex: `mass 1 s 100` (set 100 mass to 1 ID player [ALL CELLS])
`s`=Set ,`r`=Remove ,`a`=Add

**Comment by t11tanYT** [comment]
good idea

**Comment by Megabyte918** [comment]
@PrinceDark9243 The extra command are unnecessary because:
For example lets say my mass was 10k, and I want to remove 1k from it. Instead of using `mass 1 r 1000`, I could just do `mass 1 9000` instead, thus removing 1k mass from myself. The same thing applies for `mass 1 a`. Also `mass s` already exists. It's just the regular command.

**Comment by MastaCoder** [comment]
These ideas sound like Ogar-Unlimited ideas
