### ISSUE TITLE
cell color controlling minions

### ISSUE THREAD

**Issue by cowpits** [Megabyte918/MultiOgar-Edited#173]
Hi - I noticed in this new version when you hit Q to control the minions the player cell color doesn't change to Grey. In the older version 1.3.5 it did. Is there a setting for it in 1.4.2?

**Comment by Megabyte918** [comment]
@cowpits it was removed a while ago for performance reasons, see this commit: https://github.com/Megabyte918/MultiOgar-Edited/commit/5a067fb882aba14e6fe19a3c65f04bee2af2c10a
If you want it back you can add the code that was removed, I'm not going to be adding it back to the repo because it required a massive amount of code.
