### ISSUE TITLE
Changing Protocol, fix Skins?

### ISSUE THREAD

**Issue by AlexByte918** [Megabyte918/MultiOgar-Edited#194]
Tittle. HOW TO CHANGE PROTOCOL?

**Comment by MastaCoder** [comment]
on the CLIENT OR ON THE SERVER?

**Comment by AlexByte918** [comment]
@MastaCoder both of them

**Comment by Megabyte918** [comment]
@AlexByte918 Changing protocol won't fix skins.
To change the protocol connect with a different client that uses a different protocol. There is no need to change the protocol with the server because MultiOgar uses multi-protocol. In other words, whatever protocol you connect with the server will adjust to.
