### ISSUE TITLE
What is the code to make popsplits easier?

### ISSUE THREAD

**Issue by koda** [Megabyte918/MultiOgar-Edited#253]
HI can anybody please help me to make popsplits easier thank you :)

**Comment by FantasyIsBae** [comment]
Please look through the other issues as there is no point repeating this the 100th time 

> Fantasy

**Comment by Tyler3D** [comment]
@koda Change your config to this:

`# MultiOgar configurations file
# Lines starting with number sign (#) are comments

# [NOTE]
# MultiOgar uses cell size instead of cell mass to improve performance!
# In order to get the cell size from mass value, you need to calculate using this formula:
#     size = SQRT( mass * 100 )
#
# For example, to set start mass = 43:
#     size = SQRT( 43 * 100 ) = SQRT( 4300 ) = 65.57
# Set playerStartSize = 66
#
# Also, you can use the following syntax to specify mass:
#     playerStartSize = massToSize(43)
# It will be automatically converted to 66

# [LOGGING]
# logVerbosity: Console log level (0=NONE; 1=FATAL; 2=ERROR; 3=WARN; 4=INFO; 5=DEBUG)
# logFileVerbosity: File log level
logVerbosity = 4
logFileVerbosity = 5

# [SERVER]
# serverTimeout: Seconds to keep connection alive for non-responding client
# serverWsModule: WebSocket module: 'ws' or 'uws' (install npm package before using uws)
# serverPort: Server port which will be used to listen for incoming connections
# serverBind: Server network interface which will be used to listen for incoming connections (0.0.0.0 for all IPv4 interfaces)
# serverTracker: Set to 1 if you want to show your server on the tracker http://ogar.mivabe.nl/master (check that your server port is opened for external connections before setting it to 1)
# serverGamemode: 0 = FFA, 1 = Teams, 2 = Experimental, 3 = Rainbow, 4 = Last Man Standing
# serverBots: Number of player bots to spawn (Experimental)
# serverViewBase: Base view distance of players. Warning: high values may cause lag! Min value is 1920x1080
# serverMinScale: Min scale for player (low value leads to lags due to large visible area for big cell)
# serverSpectatorScale: Scale (field of view) used for free roam spectators (low value leads to lags, vanilla=0.4, old vanilla=0.25)
# serverStatsPort: Port for the stats server. Having a negative number will disable the stats server.
# serverStatsUpdate: Update interval of server stats in seconds
# serverMaxLB: Controls the maximum players displayed on the leaderboard.
# serverChat: Allows the usage of server chat. 0 = no chat, 1 = use chat.
# serverName: Server name, for example "My great server"
# serverWelcome1: First server welcome message
# serverWelcome2: Second server welcome message (optional, for info, etc)
serverTimeout = 300
serverWsModule = "ws"
serverMaxConnections = 128
serverPort = 443
serverBind = "0.0.0.0"
serverTracker = 0
serverGamemode = 0
serverBots = 0
serverViewBaseX = 1920
serverViewBaseY = 1080
serverMinScale = 0.15
serverSpectatorScale = 0.4
serverStatsPort = 88
serverStatsUpdate = 60

# [CLIENT]
serverMaxLB = 10
serverChat = 1
serverChatAscii = 1
serverName = "MultiOgar-Edited #1"
serverWelcome1 = "Welcome to MultiOgar-Edited!"
serverWelcome2 = ""

# [ANTI-BOT]
# serverIpLimit: Controls the maximum connections from single IP (use 0 to disable)
# serverMinionIgnoreTime: minion detection disable time on server startup [seconds]
# serverMinionThreshold: max connections within serverMinionInterval time period, which will not be marked as minion
# serverMinionInterval: minion detection interval [milliseconds]
# serverScrambleLevel: Toggles scrambling of coordinates. 0 = No scrambling, 1 = lightweight scrambling. 2 = full scrambling (also known as scramble minimap), 3 - high level scrambling (no border)
# playerBotGrow: Cells greater than 625 mass cannot grow from cells under 17 mass (set to 1 to disable)
serverIpLimit = 4
serverMinionIgnoreTime = 30
serverMinionThreshold = 10
serverMinionInterval = 1000
serverScrambleLevel = 0
playerBotGrow = 0

# [BORDER]
# Border size (vanilla 14142.135623730952)
borderWidth = 14142.135623730952
borderHeight = 14142.135623730952

# [FOODS]
# Each interval is 1 tick (40 ms)
# foodMinSize: vanilla 10 (mass = 10*10/100 = 1)
# foodMaxSize: vanilla 20 (mass = 20*20/100 = 4)
foodMinSize = 10
foodMaxSize = 20
foodMinAmount = 1000
foodMaxAmount = 2000
foodSpawnAmount = 30
foodMassGrow = 1
spawnInterval = 20

# [VIRUSES]
# virusMinSize: vanilla 100 (mass = 100*100/100 = 100)
# virusMaxSize: vanilla 140 (mass = 140*140/100 = 196)
virusMinSize = 100
virusMaxSize = 140
virusMinAmount = 50
virusMaxAmount = 100

# [EJECTED MASS]
# ejectSize: vanilla 37 (mass = 37*37/100 = 13.69)
# ejectSizeLoss: Eject size which will be substracted from player cell (vanilla 43?)
# ejectCooldown: Tick count until a player can eject mass again (1 tick = 40 ms)
# ejectSpawnPercent: Chance for a player to spawn from ejected mass. 0.5 = 50% (set to 0 to disable)
ejectSize = 38
ejectSizeLoss = 43
ejectCooldown = 3
ejectSpawnPercent = 0.5

# [PLAYERS]
# Reminder: MultiOgar uses cell size instead of mass!
#       playerStartMass replaced with playerStartSize
#
# playerMinSize: vanilla 32 (mass = 32*32/100 = 10.24)
# playerMaxSize: vanilla 1500 (mass = 1500*1500/100 = 22500)
# playerMinSplitSize: vanilla 60 (mass = 60*60/100 = 36)
# playerStartSize: Start size of the player cell (mass = 32*32/100 = 10.24)
# playerSpeed: Player speed multiplier (1=normal speed, 2=twice faster)
# playerRecombineTime: Base time in seconds before a cell is allowed to recombine
# playerDecayRate: Amount of size lost per second
# playerDisconnectTime: Time in seconds before a disconnected player's cell is removed (Set to -1 to never remove)
playerMinSize = 66
playerMaxSize = 2500
playerMinSplitSize = 60
playerStartSize = 66
playerMaxCells = 512
playerSpeed = 1
playerDecayRate = .002
playerRecombineTime = 30
playerMaxNickLength = 15
playerDisconnectTime = 60

# [MINIONS]
# Custom minion settings
# minionStartSize: Start size of minions (mass = 32*32/100 = 10.24)
# minionMaxStartSize: Maximum value of random start size for minions (set value higher than minionStartSize to enable)
# disableERTP: Whether or not to disable ERTP controls for minions. (must use ERTPcontrol script in /scripts) (Set to 0 to enable)
# disableQ: Whether or not to disable Q controls for minions. (Set 0 to enable)
# serverMinions: Amount of minions each player gets once they spawn
# defaultName: Default name for all minions if name is not specified using command (put <r> before the name for random skins!)
# collectPellets: Enable collect pellets mode for minions. To use, use the ERTPcontrol script and press "P"
minionStartSize = 64
minionMaxStartSize = 32
disableERTP = 0
disableQ = 1
serverMinions = 0
defaultName = "minion"
collectPellets = 1

# [LAST MAN STANDING]
# When it starts/ends is decided randomly just like vanilla, based on the values below
# lastManStandingShortest: Shortest amount of time possible before LMS happens in minutes
# lastManStandingLongest: Longest amount of time possible before LMS happens in minutes
# lastManStandingKickShortest: Shortest amount of minutes till kicking time
# lastManStandingKickLongest: Longest amount of minutes till kicking time
lastManStandingShortest = 60
lastManStandingLongest = 120
lastManStandingKickShortest = 30
lastManStandingKickLongest = 60
`

**Comment by Tyler3D** [comment]
Now you 360 NO SCOPE HAX POPSPLIT EVERYONE (NOTCLICKBAIT)

**Comment by Tyler3D** [comment]
if you want 16 split back use OgarUl

**Comment by AlexandriteErikParacelsus** [comment]
wtf is this
