### ISSUE TITLE
TEAMING BOTS

### ISSUE THREAD

**Issue by t11tanYT** [Megabyte918/MultiOgar-Edited#27]
PLEASE

**Comment by Megabyte918** [comment]
The bots are fine as they are, I will try to make them smarter in the future (splitting when they are big and other things), but teaming I cannot do. It would increase lag and CPU usage by a ton due to all the calculations you would need to make them team (splitrunning and all that). Also, this is an OgarUnlimited feature, which is partially the reason why its so laggy, so I am not going to add it.
