### ISSUE TITLE
Direction for Mobile Physics

### ISSUE THREAD

**Issue by PrinceDark9243** [Megabyte918/MultiOgar-Edited#274]
is there a way to eject mass at certain direction without move but getting push into us i know you dont understand me but here is the video
https://www.youtube.com/watch?v=Rdn8tRv6XLU

watch form 4:16 you will understand me(this the part of Mobile Physics too) and it is Essential!

**Comment by PrinceDark9243** [comment]
it can be possible make server see if player cursor is stop moving in certain direction the eject mass go to cursor direction!

**Comment by Megabyte918** [comment]
@PrinceDark9243 There is no way to stop yourself unless you put your mouse in the center of your cell to stop moving or unless you use the freeze command. If you put your mouse in the center of your cell your only supposed to eject mass in some specific directions, not the way your mouse is facing because it is in the center of your cell. As for the freeze command you are not supposed to be able to eject mass or split. I am not going to be adding every single feature from mobile here as to not cause lag.

**Comment by PrinceDark9243** [comment]
u made me SAD!

**Comment by MastaCoder** [comment]
wtf lol
