### ISSUE TITLE
minion with same name

### ISSUE THREAD

**Issue by PsycoYT** [Megabyte918/MultiOgar-Edited#303]
in cell.sh (gamemode SOLO PARTY) the bots
Arrive with the name of the owner and with the same skin

**Comment by AlexHGaming** [comment]
You can do this:
minion [ID] [amount] [skinname] [name]

**Comment by AlexHGaming** [comment]
It shouldn't glitch. Everything's the same even if you are on a different client (apart from the macros and that)

**Comment by Megabyte918** [comment]
@PsycoYT you can do what @AlexHGaming said, or you can change the value of "name" in the [minion command](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/modules/CommandList.js#L168) to this:
<pre>
client.getFriendlyName();
</pre>
So by default it sets the minion's name to the person your giving them to's name

**Comment by AlexHGaming** [comment]
Or go to the gameserver.ini, go to the minions bit then change the 'defaultname' to whatever  you want
Also above that there's a 'serverminions' option, which gives everyone (excluding bots) the amount of minions you set. @Megabyte918 @PsycoYT

**Comment by PsycoYT** [comment]
@Megabyte918  how to change that?

**Comment by PsycoYT** [comment]
```
 for (var i = 0; i < add; i++) {
                        gameServer.bots.addMinion(client.getFriendlyName);
                    } 
```

**Comment by AlexHGaming** [comment]
Go to your server files
Go to src
Go to gameserver.js
Go to line 168
Copy Megabyte's code into there.

**Comment by AlexHGaming** [comment]
Commandlist.js*
oops not gameserver.js lmao

**Comment by josefredohd** [comment]
Then if I put what I put MegaByte918 the minions will be called as the player?

**Comment by AlexHGaming** [comment]
They will be called what you put in the commandlist.js

**Comment by AlexHGaming** [comment]
`client.getFriendlyName();`
in between the 2 brackets insert the name, like this
`client.getFriendlyName(fjkd);`
I think!
Sorry I ain't no coder lol
Hope I did well

**Comment by Megabyte918** [comment]
The parameters for the `addMinion` function are `owner` and `name`. 
The `owner` of the minions comes from playertracker, so no need to edit that value. 
And `name` comes from the minion command in CommandList, or if no name is specified, comes from gameserver.ini (defaultName config)

`addMinion` is called in CommandList when the minion command is entered. Using `gameServer.bots.addMinion(client, name);`, you can specify any name you want. The `name` variable at the top of the command specifies any names sent through the console, if you want to specify a single name through adding minions you can do for example with my name: 
`gameServer.bots.addMinion(client, "megabyte918");`. Just make sure it is surrounded in quotes. 
`client.getFriendlyName();` gets the current player's name, it is not called using parameters. So calling it with anything in between the parenthesis won't do anything.

**Comment by PsycoYT** [comment]
i not understood

**Comment by AlexHGaming** [comment]
Close #310
It has completely nothing to do with the project.

**Comment by AlexHGaming** [comment]
@PsycoYT Basically where Megabyte put `gameServer.bots.addMinion(client, "megabyte918");` The minions will be called 'megabyte918' because that's what's been put in the commandlist.js
Or you can just use 2 sampler versions.

- Type in the console `minion [ID] [Amount] [Skinname] [Name]` (change the brackets to what your choice is.)
- Going into the gameserver.ini, find this part: `
# [MINIONS]
# Custom minion settings
# minionStartSize: Start size of minions (mass = 32*32/100 = 10.24)
# minionMaxStartSize: Maximum value of random start size for minions (set value higher than minionStartSize to enable)
# disableERTP: Whether or not to disable ERTP controls for minions. (must use ERTPcontrol script in /scripts) (Set to 0 to enable)
# disableQ: Whether or not to disable Q controls for minions. (Set 0 to enable)
# serverMinions: Amount of minions each player gets once they spawn
# defaultName: Default name for all minions if name is not specified using command (put <r> before the name for random skins!)
# collectPellets: Enable collect pellets mode for minions. To use, use the ERTPcontrol script and press "P"
minionStartSize = 64
minionMaxStartSize = 64
disableERTP = 0
disableQ = 1
serverMinions = 0
defaultName = ""
collectPellets = 0` Then basically change the `serverMinions = 0` change the 0 to the amount you want per player.
`defaultName` will be the name of the minions.
Hope this helps :)

**Comment by AlexHGaming** [comment]
Oops I messed up a bit of the highlighting. Doesn't matter

**Comment by suprix** [comment]
Em it doesn't work for me...I am just getting some *socket* error
