### ISSUE TITLE
@MasterCoder plz help me

### ISSUE THREAD

**Issue by Jhair2015** [Megabyte918/MultiOgar-Edited#321]
![captura de pantalla 117](https://cloud.githubusercontent.com/assets/18153674/21579026/9dbc7396-cf66-11e6-9bf4-11c18d1ef60b.png)

Please @MastaCoder @Megabyte918  Help Me, I know it has nothing to do with the project, but after I reply, I close this.

I bought Digital Ocean, but I do not know where to start D:

**Comment by MastaCoder** [comment]
root is the username of the root account when logging in. Use the password that has been set by the droplet to login to it. It's best to make another user account so that if you do get hacked, the user does not have root access. Then you pretty much login, wget or use git to download the files, install node using apt-get or yum (ubuntu and debian or centos and fedora?).

It's a pretty long process to get everything setup since a lot of Linux is not even close to how Windows works. I'm guessing this is your first time using the Linux terminal since logging in is literally the basics. 

http://www.makeuseof.com/tag/a-quick-guide-to-get-started-with-the-linux-command-line/ - For getting started with the command line.

There are instructions on the readme on how to run the file on Linux with sample commands, try them out after installing all the necessary parts of it.

@Gimmo also seems to know a bit about this, try him as well. Good luck.

**Comment by Jhair2015** [comment]
@MastaCoder  Thanks, is my first time ussing this

Is Linux

**Comment by ZfsrGhS953** [comment]
Also, keep in mind that you bought a VPS with only 1TB tranfer. If your server has 128 players, MultiOgar-Edited will reach that amount in 3 days.

**Comment by ZfsrGhS953** [comment]
You need to have 12 players or less playing on your server on average to keep it up 24/7

**Comment by MastaCoder** [comment]
I managed to get around 10TB+ of usage per month from around 200 players on at once on average.

**Comment by Jhair2015** [comment]
Fuck my life :(

**Comment by systemroot** [comment]
just playing too much one day i used 3TB in 24/H :scream:
