### ISSUE TITLE
Gota.io Popsplits

### ISSUE THREAD

**Issue by freaky767** [Megabyte918/MultiOgar-Edited#332]
Is it possible to make the same popsplit mechanics to gota?

**Comment by PsycoYT** [comment]
yeaa please make like gota.io :)

**Comment by AlexHGaming** [comment]
I'm actually saying this, but I would like this feature too.
But I'm not sure if @Megabyte918 can estimate it.

**Comment by Tyler3D** [comment]
@AlexHGaming @PsycoYT Mess around with the number of these two lines
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/entity/Virus.js#L52-L53

**Comment by Tyler3D** [comment]
Then save the virus.js file than, try popsplits

**Comment by Tyler3D** [comment]
I've never played gota.io so, obviously Idk the numbers

**Comment by Megabyte918** [comment]
@freaky767 I do not know how the popsplit mechanics work in gota.io. But do what @Tyler3D said and you should be fine

**Comment by freaky767** [comment]
oh ok.

**Comment by AlexHGaming** [comment]
I'm a noob at code, but how do you increase the chance on those lines?
Increase numbers? Decrease?

**Comment by Megabyte918** [comment]
@AlexHGaming You must edit the ratio to affect popsplits the way you want it.
<pre>
var v = c.isMoving ? 4 : 4.5; << check if the player's cells are in boosted mode (player is being popsplitted), if so, decrease the mult to 4 (so there is a higher chance of more cells popping out). Or else it is default 4.5
var exp = (Math.random() * (v - 3.33)) + 3.33; << controls how many [big] cells popout by selecting a random value in between "v" and 3.33 using Math.random();. Decrease: more big cells popout. Increase: less big cells popout.
exp = 2;  << controls the size of the "big" cells that popout. decrease: increase the size of cells that popout. increase: decrease the size of cells that popout
</pre>

**Comment by Tyler3D** [comment]
oh I dumb xD

**Comment by Tyler3D** [comment]
cause could generate a negative number and or zero

**Comment by Tyler3D** [comment]
there's a potential memory leak

**Comment by Tyler3D** [comment]
<--- Last few GCs --->

   32236 ms: Scavenge 965.4 (1004.3) -> 965.4 (1004.3) MB, 0.0 / 0 ms (+ 1.0 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
   32430 ms: Mark-sweep 965.4 (1004.3) -> 582.4 (620.7) MB, 194.0 / 0 ms (+ 1.0 ms in 2 steps since start of marking, biggest step 1.0 ms) [last resort gc].
   32571 ms: Mark-sweep 582.4 (620.7) -> 582.1 (620.7) MB, 141.0 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000002F5952B4639 <JS Object>
    2: onEaten [C:\Users\Tyler\Desktop\MultiOgar-Edited-master\src\entity\Virus.js:~30] [pc=000001BF41DF86AD] (this=0000004B4C0D7031 <a Virus with map 000003D39594C821>,c=0000024AE4C6CCA1 <a PlayerCell with map 000003D395953C51>)
    3: resolveCollision [C:\Users\Tyler\Desktop\MultiOgar-Edited-master\src\GameServer.js:878] [pc=000001BF42428412] (this=00000253941BB279 <a GameServer with map 00...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
