### ISSUE TITLE
This is not an issue, but add this please @Megabyte918

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#349]
I'm completely confused around with the pull request thingy, don't know any other option but:
I want to add a new gameserver.ini line.
`ImprovedPopsplitting`
`Enchancing the chance of hitting a popsplit.`
Where you do the following:
virus.js
Line 52 (somewhere like there)
`var v = c.isMoving ? 4 : 4.5;` to:
`var v = c.isMoving ? 4 : 4.2;` or maybe (up to you Megabyte) `var v = c.isMoving ? 4 : 4.0;`
Sorry, I know nothing about Github, and extracting files and that. I'll remove this if I get an answer from @Megabyte918.
I'd like having a feature like this, new people to the project might like it too. Like I said, I know HARDLY anything about doing stuff about this, which is why I put 'virus.js' with the lines.

**Comment by Tyler3D** [comment]
@AlexHGaming That's good in all but, lag

**Comment by Tyler3D** [comment]
Changing physics by config = lag

**Comment by AlexHGaming** [comment]
But people with fast computers could actually like this feature... o_o

**Comment by Tyler3D** [comment]
@AlexHGaming That's not the problem. The problem is that every time you hit a virus you lag even if the config is off.

**Comment by Tyler3D** [comment]
I know, javascript is a jerk when it comes to performance

**Comment by AlexHGaming** [comment]
This feature could also be added because if some people are only here for the popsplits (I'm here for minions and banter) then this could be a feature for them. Yeah I know what you mean by the performance. @Megabyte918 could add at the end of the description 'the lower the value, the more lag'
Instead of putting '1' for 'on' you could make a number below 4.5 for people to edit what their preferred setting is.

**Comment by AlexGallegos908** [comment]
@AlexHGaming Good idea bro

**Comment by Jhair2015** [comment]
@AlexGallegos908  Hey, send your skype.

**Comment by AlexGallegos908** [comment]
@Jhair2015 No te encontre V: buscame como Alex Gallegos tengo una imagen de una skin de agar

**Comment by AlexGallegos908** [comment]
@Jhair2015 https://www.facebook.com/profile.php?id=100012851407484 :v dios creo que skype nos odia

**Comment by Jhair2015** [comment]
@AlexGallegos908  Jaja, ya te mande solicitud, Soy: Jimmy Morales

**Comment by Megabyte918** [comment]
I don't think a config for it is a good idea, considering how many if statements and random numbers are generated depending on said if statements when you hit a virus. Adding a config to said numbers would decrease performance on impact with a virus because it would need to check what the value of the higher number is from gameserver.ini every time

But, if you would like to do so you can do this:

Virus.js:
<pre>
// "this.gameServer.config.configName" defines the first number
var v = c.isMoving ? this.gameServer.config.configName : 4.5;
</pre>
GameServer.js: 
Add the new config to the config object `this.config`
<pre>
configName: val,         // insert description
</pre>
gameserver.ini:
<pre>
# configName: description
configName = val
</pre>
