### ISSUE TITLE
[CLOSE!]

### ISSUE THREAD

**Issue by AlexGallegos908** [Megabyte918/MultiOgar-Edited#350]
Check my config
minionStartSize = 42
minionMaxStartSize = 62
disableERTP = 0
disableQ = 0
serverMinions = 0
defaultName = "minion"
collectPellets = 0

**Comment by Jhair2015** [comment]
En que cliente lo probaste? @AlexGallegos908

**Comment by Megabyte918** [comment]
@AlexGallegos908 Any errors in webconsole?

**Comment by AlexHGaming** [comment]
This doesn't work because (these are the answers to 2 of the possibilites.)
`Question: I have no ERTP tampermonkey, but I have disableQ = 1 and disableERTP = 0 but it's not working? What's going on?`
`Answer: ERTP doesn't support the vanilla client. The ERTP only works on other clients which supports it.`
OR:
`Question: I have an ERTP script, but when DisableQ = 0 and DisableERTP = 0, nothing is happening what is going on?`
`Answer: Do these 2 things;
1. Make sure DisableQ = 1 and DisableERTP = 0 is active.
2. Reinstall the tampermonkey script and try again.`
Hope this helps!!!

**Comment by AlexGallegos908** [comment]
@AlexHGaming Thanks! im nox wanna close

**Comment by Megabyte918** [comment]
@AlexGallegos908 If you want to close an issue, click the close or close and comment button at the bottom of the comment box :)

**Comment by AlexHGaming** [comment]
Anytime 👍

**Comment by AlexHGaming** [comment]
Anytime 👍
