### ISSUE TITLE
Random Minion?

### ISSUE THREAD

**Issue by raphyjb** [Megabyte918/MultiOgar-Edited#385]
No issues here. i find that @Megabyte918 really takes alot of time, and effort to bring something we all love. I dont know what the motives are but its really nice of you and id like to thank you for that. 
--
There is 2 things that im not sure if u could change.
When u split into 200 pieces, and there a huge lag spikes.. makes server go from 7ms to 81ms, makes everyone lag till that person is completly eaten. I know for sure Alis.io fixed that..
Also u said <r> for random skin is right, but the problem is its always the same skins coming to you and not new skins. Example i connect to my game ill get basketball skin and for 1 of my minions, well his ganna stay basket ball till i quit the game.

Thank you for taking ur time

**Comment by Jhair2015** [comment]
good idea.

**Comment by Agarian** [comment]
So you're saying you want minions (or anybody) when using `<r>` to get a different skin every time they respawn? I'll have to admit, it seems logical, but this probably wouldn't fit well with playerbots.

**Comment by Megabyte918** [comment]
> When u split into 200 pieces, and there a huge lag spikes.. makes server go from 7ms to 81ms, makes everyone lag till that person is completly eaten. I know for sure Alis.io fixed that..

It has always been that way. There is no easy fix, there is a need to rewrite the collision engine (again) in order to not have lag. Also I'm pretty sure Alis.io would have pretty powerful servers made to handle that sort of stuff

> Also u said for random skin is right, but the problem is its always the same skins coming to you and not new skins. Example i connect to my game ill get basketball skin and for 1 of my minions, well his ganna stay basket ball till i quit the game.

I thought of implementing this, but the way it is now is much more performant. If The server were to choose a random skin from a list of +300 skin names every time a bot/player/minion spawned, it would cause some serious performance issues

**Comment by Andrews54757** [comment]
@Megabyte918 With the 200 pieces issue, I dont think it would be hard to solve it

**Comment by Megabyte918** [comment]
How so?

**Comment by Andrews54757** [comment]
So I tried it, (with probably 3000 pieces) and it destroyed my server,
<img width="1274" alt="screen shot 2017-01-09 at 9 45 38 pm" src="https://cloud.githubusercontent.com/assets/13282284/21792130/92a6e936-d6b5-11e6-8422-5d2172a33aed.png">

And I found out the problem was with the collision. And here is a description why

## Explanation and solution

If I have a lot of cells clustered togethor, then the quadtree/hashbounds find function will return a lot of cells. So the efficiency would be less by a lot. I think the best way to solve this, is to have a "dynamic" collision system.

**Comment by Andrews54757** [comment]
A dynamic collision system is hard to explain, but is simple enough. It is where checking things, are like a chain

**Comment by Andrews54757** [comment]
So for example, If I have cells a, b, and c, in the normal configuration, you would loop through all nodes in that list for every node to check for collisions. It goes like this:

1. Check for A, ->
   * check A,B,C for collision
2. Check for B ->
   * check A,B,C for collision
3. Check for C ->
   * check A,B,C for collision


As you can see, this is very inefficient, and is the method everyone uses. A dynamic system would look like this:

1. Check for A
   * check B,C for collision
2. Check for B
  * Check C for collision
3. Dont do anything for C as it was already checked

**Comment by Andrews54757** [comment]
@Megabyte918 ?

**Comment by Andrews54757** [comment]
@Megabyte918 However though, I attempted to try this multiple times, and I failed. But I feel like the answer is near

**Comment by Megabyte918** [comment]
Well I mean if you failed to do it I probably will too haha, but can't hurt to try!

**Comment by raphyjb** [comment]
@Megabyte918 alright, but Andrew (or legitsoulja) did make the </random> for the skins so that each time u respawn theres a new skin, but im not sure for the lag it brought, because i tried to take off the skins at all and doesnt change anything.

**Comment by Andrews54757** [comment]
@Megabyte918 I think you should create a plugin system. That way, you can add more features without making efficiency worse (Key thing for OpenAgar, basically no features come in the box). So I give you permission to take OgarUl's plugin system.

**Comment by Andrews54757** [comment]
@Megabyte918 Also, I succeeded in creating a dynamic collision system, however though, the system is not so efficient

**Comment by raphyjb** [comment]
@Andrews54757 idea of making plugin system is good idea! Is it possible to post your dynamic collision system so i cant try it?
