### ISSUE TITLE
Can you add plugins?

### ISSUE THREAD

**Issue by iTzTati** [Megabyte918/MultiOgar-Edited#403]
Im asking if you can add plugins and a support to AJS-development's OgarUL-Plugin-Library(git:  https://github.com/AJS-development/OgarUL-Plugin-Library )?  If you can this is gonna be amazing.
PD: I want this to a console online. If i host it so admins can access to the console and they can do commands too. Just like the plugin.

**Comment by Andrews54757** [comment]
@Megabyte918 And I give you permission to take OgarUL's plugin system. I wont complain.

**Comment by Andrews54757** [comment]
@Megabyte918 Except dont take the plugins themselves. They are the hard work of LegitSoulja. You can have MultiOgar be compatible with OgarUL plugins, so they ca be used, but dont change the code of the plugins as the credit belongs to him

**Comment by iTzTati** [comment]
@Andrews54757 Thanks you for giving him permissions

**Comment by RelTakeover** [comment]
@Megabyte918  yes please add plugins

**Comment by Megabyte918** [comment]
I'm not planning on updates any time soon.

**Comment by PrinceDark9243** [comment]
@Megabyte918  dont add plugins it will make the MultiOgar-ED Like OgarUl and your Goal is to Get Vanilla Physics not other

**Comment by MastaCoder** [comment]
@PrinceDark9243 Goal is for vanilla feel without extra features? Are you sure you're the right person to be saying that?

#345, #264, #168

**Comment by systemroot** [comment]
@Megabyte918  i don't recommend it.

if that goes like that then what? what's the idea of this project? what will be the difference? because adding to much code files plugins etc games will go laggy.
if you want plugins bla bla. go and get ogarul. 

at last what plugin do you want? why is even needed when ogarul creators don't allow anything else but just OgarUL ex on statistic, i saw one time someone put Mg-edited on server track and he got deleted and legitsoulja said that is only for OgarUL not for Multiogar, Multiogar-edited, or ogar or anything else.

**Comment by MastaCoder** [comment]
+1 +1 +1

**Comment by Megabyte918** [comment]
Agreed. Also any plugins from the library will not be compatible with this fork of MultiOgar.

**Comment by Andrews54757** [comment]
@systemroot Plugins do not change lag. Because they are loaded on startup and thats it.

**Comment by Megabyte918** [comment]
I don't want this project to be like OgarUL.

**Comment by AlexHGaming** [comment]
@Megabyte918 haha ikr
Go report it on the OgarUL page

**Comment by ZfsrGhS953** [comment]
What's the point of the plugin system? It only adds more lag by calling a lot of plugin functions. And @Megabyte918 said that the goal of this project is to be even faster than original MultiOgar, and adding it would set it back a long way.

**Comment by Megabyte918** [comment]
Having many plugins do not necessarily affect performance (depending on the plugin), but having many plugins and having to load/check for them at startup does lead to slow startup times. Thank you @Andrews54757 for giving me permission to use OgarUL's plugin system, that was really nice of you :) But I do not think I am going to implement this. The amount of code required to load a plugin system is massive, not including all of the new plugins I (or other people) would have to make (seriously look at the size of OgarUL's plugin system). It could have some unintended side-affects on performance. The goal of this project was to have better performance than MultiOgar, vanilla physics, and many features while also not becoming OgarUL. Adding this would set it back on two of those. The plugins from the library could easily be implemented without the use of loading it through a plugin system. If you would like any features to be added, please request them individually rather than just "a plugin system". Because nobody is going to add plugins.

**Comment by Andrews54757** [comment]
@Megabyte918 Yeah, OgarUL's plugin system is pretty big. Mostly because it uses folders as plugins and other things. Was my first plugin system I ever wrote on JS. @Megabyte918 If you want though, I can create a very optimised plugin system for you.

**Comment by systemroot** [comment]
i'm not a nodejs guy. so thats why i didn't reply you @Andrews54757 
but is something which i don't understand.
if nodejs is based on cpu which mean every thing even if a simple word will heat some cpu even if 0.00001%
but what if we have a plugin which will executed on startup and also will executed every time when a player respawn and we have something like 100player on server. doesn't that change lag?

**Comment by Andrews54757** [comment]
@systemroot No, it doesnt change lag unless you install a plugin that does many calculations on that event. Calling it itself doesnt cause lag, but the plugin might. So if you have no plugins installed, then you would have no effect

**Comment by PrinceDark9243** [comment]
@MastaCoder That are my Suggestion not EXTRAAAAAAAAAAAA FEATURES But what @Megabyte918 Said Plugins will lag the server.

**Comment by PrinceDark9243** [comment]
and no one want plugin instead of others.
