### ISSUE TITLE
How to make anti team FFA

### ISSUE THREAD

**Issue by PsycoYT** [Megabyte918/MultiOgar-Edited#414]
Iike agar.io Free for all anti team

**Comment by Agarian** [comment]
Oh.

**Comment by AlexHGaming** [comment]
I found this somewhere, try finding in in the other folders.

**Comment by Luka967** [comment]
All of its traces are removed completely, it needs to be rewritten again.
And it's practically useless because this client is designed for maximum responsiveness with a lot of player interactions.
Ogar's anti-teaming is more complex than this one but can be looked in for re-implementation.
@Megabyte918 Close?

**Comment by Agarian** [comment]
I dislike anti-teaming TBH

**Comment by AlexHGaming** [comment]
@Agarian Haha :P

**Comment by RelTakeover** [comment]
and my solution ? -.-
