### ISSUE TITLE
How to do?

### ISSUE THREAD

**Issue by RelTakeover** [Megabyte918/MultiOgar-Edited#449]
I would like to spawn safely and very close to the last player who gave points or gave him split

**Comment by Megabyte918** [comment]
@RelTakeover Can you explain a bit better please? I don't understand what you are trying to say.

**Comment by ZfsrGhS953** [comment]
@Megabyte918 He wants to make players respawn near their death point.

**Comment by RelTakeover** [comment]
yes

**Comment by Jhair2015** [comment]
@RelTakeover You could try "ejectSpawnPercent" in gameserver.ini

It's the only thing that occurs to me lol.

**Comment by Megabyte918** [comment]
@RelTakeover You can try storing the X and Y coordinates of when the player died, then spawn them at those coordinates once they press play again. But something like this would reduce performance due to the server storing the coordinates of every player who dies, and it might not work because every player needs an individual spawning position

**Comment by RelTakeover** [comment]
@Megabyte918  you can help me? please

**Comment by Megabyte918** [comment]
@RelTakeover [Here you go](https://www.google.com/search?q=javascript%20tutorial) ;)
