### ISSUE TITLE
How to add player commands?

### ISSUE THREAD

**Issue by luckservers** [Megabyte918/MultiOgar-Edited#464]
So I was wondering, that I wanna make commands for my admins. Like /minion /mass /kick /ban

**Comment by Megabyte918** [comment]
Port them over from CommandList.js to PlayerCommand.js.

**Comment by luckservers** [comment]
So I just copy and paste from CommandList.js to PlayerCommand.js?

**Comment by luckservers** [comment]
It didnt work...

**Comment by Megabyte918** [comment]
Yes, but you need to adjust the code so that it works in PlayerCommand, along with adding the userrole permissions and all that.
 Take a look at the ones that were added [here](https://github.com/Megabyte918/MultiOgar-Edited/commit/a3eb16aa54dd9bb491807766a0ed7a5228cbe95c), they were ported from CommandList, just compare the commands from CommandList and PlayerCommand to see whats different. Either that or you can learn javascript, that way you could add any commands you want.

**Comment by luckservers** [comment]
Ok

**Comment by luckservers** [comment]
There is still errors in the code.

**Comment by Megabyte918** [comment]
@luckservers Make an issue about it on his repository
