### ISSUE TITLE
Cells color

### ISSUE THREAD

**Issue by MartincoderMlg** [Megabyte918/MultiOgar-Edited#563]
looks like when players spawn they have like 10 or 12 cell colors , how to make cells have more colors .

**Comment by AlexHGaming** [comment]
This is how it looks like in vanilla agar.

**Comment by AGarRiBiA** [comment]
yeah how to make cells have a Custom Color because i have a game and i want to delete a yellow color :~

**Comment by Megabyte918** [comment]
If you are using the updates branch, you need to edit [this](https://github.com/Megabyte918/MultiOgar-Edited/blob/Updates/src/GameServer.js#L394-L406) function to change the colors that players and food spawn with. You will need to know how RGB color coding works in order to get the colors that you are looking for
