### ISSUE TITLE
Private messages

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#618]
First: The players would have their ID, next to the name
Second: 
You could send a private message to a player by selecting their ID, in OGARUL, you could do this but only from console, this would be a great advance in features of Multiogar-EDITED, without causing delay

**Comment by MastaCoder** [comment]
You know why OgarUL died?

**Comment by Megabyte918** [comment]
The features for chat and other things such as user-roles and player-commands are basically just templates for other people to develop and make their own things out of them for their own clients and such. If you want it that badly, I suggest you learn javascript, otherwise this will not be added to the project, mostly because it is 99.9% pointless and would not matter for the people who use clients that do not support chats.
