### ISSUE TITLE
Mother Cell

### ISSUE THREAD

**Issue by Gigabyte918** [Megabyte918/MultiOgar-Edited#638]
Its like Mother Cell dose not spawn mass on outer layer of the cell but inside
![image](https://cloud.githubusercontent.com/assets/17459204/23587723/3a5fa58e-01d4-11e7-986a-66b1063c02d4.png)
And when i eat mother cell its crashes
![image](https://cloud.githubusercontent.com/assets/17459204/23587729/4d36ddc6-01d4-11e7-845b-0e4b28ff4b9b.png)
Cant able to see the Crash Report [Click Here](https://cloud.githubusercontent.com/assets/17459204/23587729/4d36ddc6-01d4-11e7-845b-0e4b28ff4b9b.png)

**Comment by Megabyte918** [comment]
Food spawning issue was fixed, however I cannot reproduce the error. Try seeing if it still occurs on the latest version.

**Comment by Gigabyte918** [comment]
Dude it is latest version 1.6.0!

**Comment by Megabyte918** [comment]
@Gigabyte918 I'm saying the LATEST latest version. As in the most recent commits. I can tell you are using an outdated version because the `checkV` function has been removed and replaced with `intersects`. I could not reproduce this bug on the latest commits, have you edited anything regarding experimental mode?

**Comment by Gigabyte918** [comment]
i dident edit any thing instead of gameserver.ini

**Comment by Megabyte918** [comment]
@Gigabyte918 Please try the latest version, I can guarantee you will not get that error
