### ISSUE TITLE
Doublesplit cell switch solutions

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#644]
I'm gonna get an essay wrote at me for this, I haven't had any bugs with applying this code, try it, and can you tell me the errors with what bugs it leads to and what it disallows? My doublesplits are behaving like vanilla.

Replace these lines of code:
`var mt = m.cell._mass + m.check._mass;` 
 `   var m1 = push * m.cell._mass / mt;`
    `var m2 = push * m.check._mass / mt;`
with this:
`var mt = m.cell._mass + m.check._mass; `
` var m1 = push * m.cell._mass / mt;`
    `var m2 = m1 / mt * m.check._mass / mt;`

**Comment by AlexHGaming** [comment]
Will it drown performance?

**Comment by Jhair2015** [comment]
awesome

**Comment by AlexHGaming** [comment]
Linesplits are a bit buggy, but that's pretty much it

**Comment by MartincoderMlg** [comment]
Nice  work works perfectly but The splits don't go straight  .

**Comment by AlexHGaming** [comment]
Might get fixed by MegaByte if he can fix what's happening to the extrusion force

**Comment by AlexHGaming** [comment]
They actually do go far, higher up your split velocity (650 - 780 recommended)

**Comment by AlexHGaming** [comment]
@Megabyte918 comments?

**Comment by Megabyte918** [comment]
@AlexHGaming This method is basically the same thing as removing `m.cell.position.sub2(m.p, m2);`.
The value of `m2` is now almost zero, which means you might as well as remove that function call along with the `m2` variable because it has now become useless.

What this change leads to:
- Softer splits, they are no longer like vanilla and more like OgarUL
- Increase in splitting kickback. This also goes along with the "splits more like OgarUL" comment.
- Excess cell squishing, cells now allow for each other to go inside of each other more than they used too.
- More collision checks, because of the excess cell squishing, the cells need more extrusion force applied/resolved. This also leads to slightly lower performance but is mostly unnoticeable. 
- Changes in doublesplits. Cells may not switch order anymore, but this is due to the softer splits and excess collision checks. Which also leads to unstable doublesplits and is why they no longer go straight.
- Smaller cells will now push harder than smaller cells. Because you are adding almost* nothing to cell's position (bigger cells) and applying more force towards smaller cells.

**Comment by AlexHGaming** [comment]
@Megabyte918 I tried splitrunning in this and I realised that it's much more easier. Maybe I should mess around wirh the variable `mainloop` and see what results I get. F

**Comment by Luka967** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/entity/PlayerCell.js#L26
Try using `unshift` instead of `push`.
Theoretically it gives checking priority to newest created player cells. Since doublesplitting cell creation orders go 1 3 2 4 in most cases the first eat check is made for the top one.
My server has the same problem to a slightly lesser degree. Doing this fixed it but sometimes makes weird physics.

**Comment by AlexHGaming** [comment]
How should I define unshift?

**Comment by Luka967** [comment]
Just replace the `push` to `unshift` in that line lol

**Comment by AlexHGaming** [comment]
oh is unshift already a definement? Oh ok then lemme check

**Comment by ItzLevvie** [comment]
^^ https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/unshift

**Comment by Megabyte918** [comment]
@Luka967 Nice! Finally something that works and doesn't affect collision quality/performance in a negative way xd
Could you describe the "weird physics" you were talking about? I would like to commit this fix but I couldn't see any difference regarding the physics

**Comment by Luka967** [comment]
I don't know if it happens in m-ed too but [this](https://gyazo.com/0f82d1904abc4fbe2bce4d954e33c706) rarely happens on my server.
Third cell switches position to first.

**Comment by Megabyte918** [comment]
@Luka967 That's perfect, the same thing happens in vanilla servers

**Comment by Luka967** [comment]
Last time I played agar is 6 months ago so yeah xD

**Comment by AlexHGaming** [comment]
Now apply it @Megabyte918 
and thanks @Luka967

**Comment by Megabyte918** [comment]
Great! Now that splitting physics are complete, only things left are eject physics, collision quality, and popsplit/virus explosion physics. Then after that, there should be no difference between here and vanilla servers!

**Comment by AlexHGaming** [comment]
@Megabyte918 Things you need to look out for:
Vanilla viruses have like 3 big parts (excluding the main biggest one) then has 12 pieces that are tiny massive, about 1/4 of the big part's mass. About that anyways.

The cells are a bit bugged. Whenever I did a doublesplit when there's a tiny cell next to it, it flew off to from it's original place to the back of the 4 pieces.
All of this hassle to fix doublesplitting was to only change the `push` to `unshift` in playercell.js lmfao
