### ISSUE TITLE
New command

### ISSUE THREAD

**Issue by t11tanYT** [Megabyte918/MultiOgar-Edited#652]
repeat - (repeating commands)
repeat (time in ms to repeat commands) (how many repeats needed) (command)
needed for:
1)Realistic minions connect -  repeat 50 15 minion 1 5 <r>Name
2) auto restart - repeat 15000 99 killall
3) auto adding bots - repeat 300 150 addbot 1

**Comment by Megabyte918** [comment]
@t11tanYT 
1) There is no more "realistic minions connect" anymore because minions have been patched on the agario client, lol. besides, why would you want the server to keep adding minions? what for? sounds like lots of lag over time to me.
2) Using an internal timer to keep track of the amount of repeats needed and the time in between repeats would reduce performance. and this is almost the same as an "auto restarting" feature, which is not needed
3) why would you want to add a bot after a certain amount of time? you can just add a set amount using the addbot command directly

**Comment by AlexHGaming** [comment]
^^

**Comment by CalvinDKL** [comment]
The kill all one would be good.

**Comment by CalvinDKL** [comment]
Very useful.

**Comment by Jhair2015** [comment]
@CalvinDKL Send me to my skype what I request you (:
