### ISSUE TITLE
How to make E R T P working to others clients? 

### ISSUE THREAD

**Issue by TheDark99** [Megabyte918/MultiOgar-Edited#677]
How to make E R T P working to others clients? 
How to make E R T P working to others clients?

**Comment by TheDark99** [comment]
plsssss

**Comment by Y4ssine** [comment]
they already work for others O.o


2017-03-18 8:04 GMT+04:00 TheDark99 <notifications@github.com>:

**Comment by TheDark99** [comment]
nooo bro, dont work in astr.io dont work

**Comment by AlexHGaming** [comment]
In the tampermonkey script
Find at the start where it says @match: "agar.io" or something liike that (should be in the first 20 lines)
Copy and paste the line on a new line
Then rename "agar.io" to the url of the client.
And btw close it because i helped you anyways and it has nothing to do with the project.
@AlexandriteErikParacelsus @Megabyte918 @FantasyIsBae

**Comment by Luka967** [comment]
@AlexHGaming Use inline code notation (\`) next time to avoid mentioning other people. E.g. `@Luka967`

**Comment by TheDark99** [comment]
@AlexHGaming That does not work for other clients, it does not work in alis, astr.io and many more :/

**Comment by MastaCoder** [comment]
http://bfy.tw/Ahyx

**Comment by Tyler3D** [comment]
Lol

**Comment by Jhair2015** [comment]
lol

**Comment by AlexHGaming** [comment]
it works for my client
