### ISSUE TITLE
What's up with this issues section..

### ISSUE THREAD

**Issue by MastaCoder** [Megabyte918/MultiOgar-Edited#700]
Over the past week there have been dozens of really stupid issues popping up on this repo, Megabyte you aren't here to save us :( Is it possible to make someone else a collaborator that actually checks this place and cleanup all of these issues. There's 17 issues opened, 8 of them aren't even supposed to be there.

Now to name them: 
#651 Dead issue.
#672 I don't even wanna talk about this one.
#673 Completed issue, 3 days no response. (up-to date)
#687 OP isn't responding.
#694 Yeahhh.. Nope.
#695 I'm not even gonna say anything.
#696 Why
#697 THIS ISN'T EVEN RELATED TO AGAR.IO.

I don't know, I'm really just speaking for myself. I'm just saying the quality of issues here are just becoming ridiculously bad. Megabyte I'm not pushing you to continue modding this place, heck I even got a crap ton of school work to get to. (Now to talk about it I got a chemistry test, shite) I just wanted to see if we can get some more **active** collaborates. Someone that'll be more strict with these issues so we can see some more productive issues :) I don't know, I'm probably just speaking for myself, I just don't want this place to end up like Ogar-Unlimited is all. 

@Megabyte918 @AlexandriteErikParacelsus @FantasyIsBae

**Comment by Tyler3D** [comment]
Solution: Open an issue xD
But your right

**Comment by MastaCoder** [comment]
@Tyler3D xD I'm just waiting on Megabytes response, I'll close it right away. idk I just thought it was something to be said, it's really getting difficult to actually keep to date with the repo issues when all we see are people asking for code to be spoon fed to them.

**Comment by Tyler3D** [comment]
👍

**Comment by Tyler3D** [comment]
There should be a dedicated Question issue or forum. Instead of making issues

**Comment by Jhair2015** [comment]
@Megabyte918

**Comment by MastaCoder** [comment]
Or just teach people how to Google xD I was stuck on getting the PayPal API working on my website a couple months ago. I spent a good 3 days trying to figure it out. I finally did, the thing is I learnt so many other things while learning about it. Like using Composer, getting PHP to actually work with errors through the php.ini, how to make proper classes in php and not be stupid. 

I never like it when people actually get given code and told where to put it exactly. There's no point on learning that way 🥉 @Tyler3D

**Comment by Luka967** [comment]
> and not be stupid.

lmao

Meanwhile I'm starting to have fun with child processes xD

**Comment by Jhair2015** [comment]
learn javascript [x10000000000000]

**Comment by Tyler3D** [comment]
lol. We need lmgtfy on the readme

**Comment by Y4ssine** [comment]
well first of all ur issues are stupid for me as well ur asking for codes
all the day and u can just get them from stackoverflow
also u rarley help other people ,
so stop being Dickheadick , and chill with ur some how retard Qs for me
ty
sincerly Me


2017-03-23 14:29 GMT-07:00 Tyler3D <notifications@github.com>:

**Comment by MastaCoder** [comment]
lmao beef

**Comment by Luka967** [comment]
@Y4ssine

> well first of all ur issues are stupid for me

What issues? Even if we had one, it would be a serious one. And this is a serious one, *for us*.
Also, *for you*.

> as well ur asking for codes

How can we fix your issues if you don't give us at least something that's causing the problem to work with?

> all the day and u can just get them from stackoverflow

> What issues?

> also u rarley help other people ,

We try to but we got fed up with the insane amount of stupid issues like "config for this that these those", "make splits like ogarul/dualagar/gota/penis", "pls help me", "HOW TO ADD MINIMAP", the list continues.

> so stop being Dickheadick

Thank you for this sincere and honest compliment.

> and chill with ur some how retard Qs for me

> What issues?

Thank you.
Sincerely, Luka

**Comment by Tyler3D** [comment]
@MastaCoder 

> #651 Dead issue.
> 
Well, I guess you can cross that one off the list lol.

**Comment by Logan7432** [comment]
@Mastacoder Issue #672 Is a issue, I never had this issue with any of my other servers but just somehow I try using this server and it dosnt work. I still think it's an issue on the server side because it worked fine on cigar. Can we just code the borders how it was coded in cigar so this works?

**Comment by MastaCoder** [comment]
Cigar used point 0, 0 as top left, MultiOgar doesn't. It uses the CORRECT map making method. Thus, it's a problem with YOUR map. NOT a server side problem, if you want help with that MINIMAP then go to the place where it was MADE and ask THEM. THIS ISN'T A SERVER PROBLEM. You were told like 10 times but still want the code to fix it.

**Comment by Logan7432** [comment]
@mastacoder this is the exact clarification I needed. Every other time you have me an answer it was something smart and help not at all. And if you know how to fix the code why can't you help me fix it. I've been trying so hard for the past few week trying to get this to work, and I still can't fox it!!! So I'm not sure what I'm suppose to do here cause so many people play on my site.

**Comment by Logan7432** [comment]
Sorry for my errors I submitted before checking my typing

**Comment by Megabyte918** [comment]
Sorry I've been slacking with the issues lately, I've been very busy and hadn't had much time to interact with the community much (I know it's getting old that I keep using that as an excuse, but it's true!)

I added my friends @AlexandriteErikParacelsus and @FantasyIsBae  as collaborators to help out every now and then, or "collaborate" and interact with the community but I haven't seen either of them active in the community in a while and it's hard to contact them due to my lack of time. I really don't want to do this because their my friends, but I might have to de-add them :/
Please don't take it personally Alex and Fantasy, I wouldn't want to burden you guys with the task of maintaining this project and filling in for my slacking, you guys probably have your own stuff your busy with and don't have time for things like this. I think I'd be better off this way :/

Don't get me wrong, I love maintaining this project and I think its really fun to be able to interact with the github community around this repo, same with being able to code this server, fix bugs, answer questions, collaborate with other developers, etc. If I had the spare time to do this all day I would. 

Sorry I've not been the most active lately, I will try my best make time for this and to keep in touch with the community and with maintaining this project. I promise! 

@MastaCoder I was thinking about adding some more colalborators who can maintain the project well, but I don't know who and I have trust issues xD
Is there a way I can contact you outside of github? Discord? Skype? If you don't feel comfortable with saying it here you can email it to me (if there even is a way lol)

**Comment by AlexHGaming** [comment]
@Megabyte918 I'm actually checking this site very frequently, and I see the useless issues (I have done them in the past.) I don't think I'm going to make anymore issues anymore despite the fact of it being useless and not reading the wiki. I was the one who made the wiki in the very first place, with everyone editing it, so I did this repo a favour (adding issue templates etc)

You might want to remove @FantasyIsBae and @AlexandriteErikParacelsus' roles because I haven't seen them doing any work on the repo.

If you want to, you could add other collaborators that you actually really trust (could be @MastaCoder).

On the other side, if I was a collaborator (I doubt it), I could remove actual useless issues, dupes and solution in the wiki. I wouldn't delete like coded issues because I'll leave them open for other people to solve. But it is your opinion. Add a few trusted collabs = useless issues are gone.

**Comment by smky** [comment]
@MastaCoder I was just asking a question, completely related to the repo. I don't see why mine was put on the list...

**Comment by MastaCoder** [comment]
@Megabyte918 I was never directing Collaborator at myself 👍 I was just hoping to find someone that actually knows what they are doing to get them as a collaborator here for the issues. I've been browsing among GitHub, I found so many great repos that have their issues section all sorted out with some really good looking tags. Then I come back to my watched and see all these useless issues. It just gets annoying 🗡 

Maintaining a project is hard, I try to update Cigar, but then I got my own website and a crap ton of school work, I feel your pain! It's hard to tell people how busy you are because it's hard for them to understand how you get time together. Same boat! (look at Cigar for example, it's dead until I find some things I can really do with it)

> Sorry I've not been the most active lately, I will try my best make time for this and to keep in touch with the community and with maintaining this project. I promise!

Don't be sorry, I was just asking for some more strict moderating of this issues section. I'd just really love to get rid of most people that just ask for code, post issues not even related to the project. It's hard to sit down and answer those people instead of working on the code itself!

I have trust issues too 🥉 https://discord.gg/mUVsaCa Just join that and request to add me as a friend. I have my DM's blocked (because WAAAAY too many messages) so just request and I'll add you 😆

**Comment by Tyler3D** [comment]
^^ Case in point
https://github.com/Megabyte918/MultiOgar-Edited/issues/707

**Comment by AlexHGaming** [comment]
My discord chat = https://discord.gg/kfWtssv 
I was thinking of being a collaborator, read my commet above on why I could be added as one :D

**Comment by AlexHGaming** [comment]
@Megabyte918 ^^

**Comment by Megabyte918** [comment]
ok

**Comment by FantasyIsBae** [comment]
Have I been removed again ? @Megabyte918

**Comment by Megabyte918** [comment]
Holy crap your alive :O 
And yes, I removed you along with Alex because of reasons I stated above (sorry)

**Comment by FantasyIsBae** [comment]
>Holy crap your alive :O
yes, I removed you along with Alex because of reasons I stated above (sorry)

Don't worry about it mate , it is probably for the best . 
Sorry I haven't been active for a while as I had some issues to sort out in real life and my PC got infected with a Trojan , so basically my CPU committed suicide and I couldn't do fuck all. 

Other than that I quite enjoyed 'helping' with this project , but with my lack of time to do shit (School , Family , etc) I couldn't help at a constant rate . I will help with issues and with pulls , I'm on Skype almost everyday so text me if you want . And again sorry 😞

**Comment by Megabyte918** [comment]
@FantasyIsBae Don't be sorry! Really, it's alright. I know how it feels to busy with those things and that also leads to less time for github stuff. The reason why I un-added you guys is so you wouldn't have to worry about maintaining this project along with worrying about real-life stuff and other things that make you busy

**Comment by FantasyIsBae** [comment]
Thanks for understanding :) @Megabyte918

**Comment by MastaCoder** [comment]
> Sorry I haven't been active for a while as I had some issues to sort out in real life and my PC got infected with a Trojan , so basically my CPU committed suicide and I couldn't do fuck all.

Lemme guess, windows deactivated and you tried to activate it with a crack but ends up being a virus? xD

Anyways glad you're doing good, also. 

<h1>use discord its better than skype.</h1>
https://discord.gg/BEXsmAG

**Comment by FantasyIsBae** [comment]
@MastaCoder No I just installed the wrong program lol 
Anad yeah no problem I'll use discord 😄
