### ISSUE TITLE
Protocol

### ISSUE THREAD

**Issue by Logan7432** [Megabyte918/MultiOgar-Edited#745]
Hey! Just wondering what a protocol is and whats the difference between each one 1-4. By using the latest protocol how does it benefit the game?

**Comment by MastaCoder** [comment]
4 - old
5 - cigar supports, basically default for now.
6 - some clients use it?

everything else is not used in any client other than the latest in Agar.io.

**Comment by Logan7432** [comment]
@MastaCoder I changed my server from protocol 1 to 4 so that would help for supporting more people and bigger map? When I try to change to protocol 5 my entire site breaks. I noticed  when it was on protocol 1 and i increased my map size less players were able to join and it was laggy, is that the reason?

**Comment by MastaCoder** [comment]
1 isn't a valid and usable protocol from what I remember.

**Comment by Logan7432** [comment]
function onWsOpen() {
        var msg;
        delay = 500;
        wjQuery("#connecting").hide();
        console.log("socket open");
        msg = prepareData(5);
        msg.setUint8(0, 254);
        msg.setUint32(1, 4, true);
        wsSend(msg);
        msg = prepareData(5);
        msg.setUint8(0, 255);
        msg.setUint32(1, 1332175218, true);
        wsSend(msg);
        sendNickName();
    }
I changed this line in that code  from msg.setUint32(1, 1, true); to         msg.setUint32(1, 4, true); Is that change the protocol to 4?

**Comment by Logan7432** [comment]
every since i increased my map size the server became mad mad laggy when more people join the server

**Comment by MastaCoder** [comment]
That's only changing the protocol number you're sending.. That's not changing the protocol.

**Comment by Logan7432** [comment]
@MastaCoder How do actually change the protocol then? Would I have to rewrite everything again? And the thing above that i did, did that change anything?

**Comment by Logan7432** [comment]
Btw, I fixed that map problem :)

**Comment by MastaCoder** [comment]
A protocol is the change of the things sent to the server, yes you do need to change them. Why are you trying to run a website without even knowing the basics to websocket connections..

**Comment by Logan7432** [comment]
@MastaCoder Because of I'm running a server for my school, and I'm not that advanced yet. I'm just trying to ensure the best experience for my users.

**Comment by Logan7432** [comment]
@MastaCoder Does the cigar client have the correct protocols?

**Comment by Logan7432** [comment]
@MastaCoder Do you think the lag my server is experiencing is from the protocol stuff or internet? I have 200mbs down and 15mbs up? That should definitely hold more than 10 people without any lag, but it doesn't.

**Comment by FantasyIsBae** [comment]
@Logan7432 I will just attempt to break this down so you can visualise it better.

The server sends info to the client.
The client connects to the server .
The client displays the info sent by the server (Players, Viruses, Border , etc...), and sends some info back (Sometimes)
Its not all about the speed that you send the info it is also about how quick the clients (Or players) receive it.
If your school's Internet is slow , and your internet connection is fast the clients will have to keep falling behind and having to catch up , therefor causing lag.
If your's and your school's internet is fast then there would not be an issue .
The protocol doesn't affect speed as far as I'm aware .
Try playing around with the settings a little bit and try optimising them.
Leave the client alone because if anything you will decrease the speed.
