### ISSUE TITLE
really in the unshift update

### ISSUE THREAD

**Issue by gyeyoqu** [Megabyte918/MultiOgar-Edited#766]
in that update, now the popsplit  not working

**Comment by AlexHGaming** [comment]
in our opinions, doublesplitting is more important than popsplitting. If you want it back to before, just revert the changes in your files, we dont have to do it.

**Comment by Agarian** [comment]
I'd actually prefer working popsplits over improved doublesplits

**Comment by AlexHGaming** [comment]
Change from unshift to push then

**Comment by Megabyte918** [comment]
@gyeyoqu Please refrain from making any further issues unless they are actually LEGITIMATE issues/questions. 

You have created 39 issues on this project, 10 of which are client sided, 6 of which are invalid, 7 of which are questions that could have been easily answered without making an issue, 8 of which are duplicates of existing issues, and 3 of which are not even related to this project and are either questions/bugs for other projects. 

I want to believe you are an intelligent person I really do, just please do your research and really think before making any more issues because everyone is starting to get annoyed at all the pointless issues you are spamming. 

You've ignored my comment from #619, ignored the issue template, and still continue to spam issues. Please take this comment into consideration next time when making your next issue or it could result in a temporary ban.

Also to answer your issue, please refer to the latest pull request #723.
