### ISSUE TITLE
Random skins problem.

### ISSUE THREAD

**Issue by suprix** [Megabyte918/MultiOgar-Edited#774]
Hey, I were looking for every single closed issue but couldn't find it...
So basiclly, when I put >minion [id] [amoutOfBots] <r> [BotName]

So the problem is that only 5-6 of ex. 100 bots have random skins.
I've put about 50 skins in **Skins** folder... Any suggestion?
Thanks.

**Comment by ZfsrGhS953** [comment]
@suprix Deal with it, random skins only work correctly on the vanilla client.

**Comment by suprix** [comment]
What do you mean? Sorry I don't really know about these stuffs :|

**Comment by suprix** [comment]
You can check ogarz.ovh and it has all random skins. @ZfsrGhS953

**Comment by Tyler3D** [comment]
@suprix I'm pretty sure there are hundreds of skins. 50 Isn't enough as only 5-6 had skins

**Comment by AlexHGaming** [comment]
*cough* CLIENT SIDED *cough*

**Comment by Megabyte918** [comment]
Yep^^
Can't have all the random skins unless you've first added them all to your client.

**Comment by AlexHGaming** [comment]
whatever skinname is in the randomskins, you put in <> tags in the name.
But you have to have a client which supports the name and image of what your talking about
So if i have a fly skin for example
do <fly> name
or if you want to add it to a client
execute fly.png into the skins folder
then put <fly>
if it doesn't work (on other clients) this i because it wont support it

**Comment by Agarian** [comment]
Why hello there

**Comment by AlexHGaming** [comment]
hiya

**Comment by suprix** [comment]
:/ So basiclly I need to add about 1k+ skins to get it working? XD

**Comment by Megabyte918** [comment]
@suprix Not really, just as much as there is in the randomskins file lol

**Comment by suprix** [comment]
Um :| I've added 100 skins and turned 30 bots ... 2 of them has skins lol
