### ISSUE TITLE
Userrole not functioning.

### ISSUE THREAD

**Issue by AlexHGaming** [Megabyte918/MultiOgar-Edited#779]
![image](https://cloud.githubusercontent.com/assets/23644244/25191020/0d8b0556-2526-11e7-8954-0f03338570ac.png)

**Comment by AlexHGaming** [comment]
Ignore red writing, forgot to add recent PR.

**Comment by Megabyte918** [comment]
The userrole command does not exist in this repository.

**Comment by AlexHGaming** [comment]
it does lol. It gave people admin if you typed in 'userrole [ID] admin'

**Comment by AlexHGaming** [comment]
well it worked for me anyways

**Comment by Megabyte918** [comment]
@AlexHGaming I think you are meaning to use @Tyler3D's commandlist

**Comment by AlexHGaming** [comment]
I wasn't. Try using an older version

**Comment by Megabyte918** [comment]
@AlexHGaming are you sure it was in older versions? I don't remember ever coding/adding it let alone merging any PR's that did either. Try checking the latest version of CommandList.js and if it's not there I think you might be getting it confused for Tyler's CommandList on his repository since he's the one who created that command.
