### ISSUE TITLE
Why? Can't log into the game

### ISSUE THREAD

**Issue by DeadLord1337** [Megabyte918/MultiOgar-Edited#815]
1)**How to fix it? This button becomes active and sometimes I can play but when I'm in the game and played and died, then the button again, sometimes but often not active.**
![44](https://cloud.githubusercontent.com/assets/24901742/25725408/8502e460-3128-11e7-9864-a6704d17f08f.PNG)
![667](https://cloud.githubusercontent.com/assets/24901742/25725407/8502301a-3128-11e7-903d-2851765e5bd9.PNG)

2)+ Update:
gameserver.ini
playerMinEjectSize = 60

3)And make the font a little less of nick, and he is too big

**Comment by AlexHGaming** [comment]
1) This is because the agar client is a bit buggy. I cba to go through all the causes, as there are a lot, one is where if you play ur server, you leave it for a bit of time then return to the tab, you'd have to refresh the page.

2) We are trying to make this project like the vanilla agar

3) This is client sided.

**Comment by DeadLord1337** [comment]
Min size split and eject 36 mass... (60)

**Comment by MastaCoder** [comment]
Can anybody confirm ^^

**Comment by AlexHGaming** [comment]
And you would also have to sign out of facebook / google for it to work
