### ISSUE TITLE
add features for minions

### ISSUE THREAD

**Issue by RelTakeover** [Megabyte918/MultiOgar-Edited#83]
features as: 

- Automatic bots have the owner's name
- set the default speed of minions
- delete ''q'' with a variable
- BOT PER IP

EXAMPLE :+1: 
DisableQ = 1
DisableERT = 0

**Comment by AlexandriteErikParacelsus** [comment]
> EXAMPLE 👍
DisableQ = 1
DisableERT = 0

what is that about?

**Comment by Jhair2015** [comment]
@AlexandriteErikParacelsus  It refers to activating Minions controlled by "Q" or "E, R, T" ...

**Comment by AlexandriteErikParacelsus** [comment]
@Jhair2015 I don't get it why is it on there?

**Comment by Megabyte918** [comment]
@RelTakeover 

> Automatic bots have the owner's name

Not possible since the server only gets the player's name AFTER they have spawned with it, and the minions are added BEFORE they spawn so they will always be unnamed by default.
> set the default speed of minions

That would decrease performance with minions by quite a bit, so no.
> delete ''q'' with a variable

I don't think we need a seperate config just for Q, if people don't want it they can just remove Q functionality through PacketHandler
> BOT PER IP

See my last comment on #13
