### ISSUE TITLE
URL for local testing?

### ISSUE THREAD

**Issue by LemonDoo** [Megabyte918/MultiOgar-Edited#848]
I feel that it should be http://localhost..., but whenever I use the port 443 it gives me "Upgrade Required", which means the websocket has problems? 

I'm a little confused

**Comment by gyeyoqu** [comment]
you should use your own client - side or http://agar.io/?ip=xxx.xxx.xxx.xxx 
xxx.xxx.xxx.xxx = ur ip

**Comment by LemonDoo** [comment]
What is my own client-side? Sorry I am a noob at this

**Comment by AlexHGaming** [comment]
If you want to host your server on agar.io

Go to gameserver.ini, set the serverport, server port is located [here](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/gameserver.ini#L41), change that to whatever apart from 443. If I set it to 8080, do the following:
agar.io/?ip=127.0.0.1:8080 
Then you should be able to connect to the server that is listening on port 8080
If that doesn't work, or you want to play on a different client
do the following:
CLIENTNAME/?ip=127.0.0.1:8080
if i wanted to play on the astr.io client
astr.io/?ip=127.0.0.1:8080
Understand me?

**Comment by Luka967** [comment]
This project uses WebSockets.
WebSockets is a duplex TCP (Transfer Control Protocol) data tunnel.
A WebSocket server listens for HTTP requests first.
A HTTP request is a TCP connection that (should) give you a single output from the server, i.e. a webpage.
That HTTP connection is then converted into a WebSocket connection, overlayed by TCP, by the server. If, and only if it contains the information only a WebSocket client would send.
What you're doing with accessing http://localhost:port is sending a HTTP request to load a page and getting dropped by the server.
You need to connect through an agar-like client.

**Comment by LemonDoo** [comment]
Thank you so much guys! I'm learning a lot and I looked up tutorials on TCP and websockets.

To get an agar-like client, is there an easy way to do it? (As in make my own domain called sample.com and having sample.com/IP_ADDRESS work? 

How exactly would you do that?

**Comment by LemonDoo** [comment]
On a similar note, you say that  accessing localhost:IP cannot work because the HTTP request is not handled correctly by the local host server. Why is this?

**Comment by Luka967** [comment]
>On a similar note, you say that accessing localhost:IP cannot work because the HTTP request is not handled correctly by the local host server. Why is this?

By default, accessing http://localhost (or pretty much anything requesting the HTTP protocol), without giving the port number will try to access port 80, or 443 if it's http secure (HTTPS).
Webservers will parse the path you've given (`/test.html` of `http://localhost/test.html`) and try to load that file.
WebSocket servers on the other hand, are just listeners for upgrading the connection to WebSockets. They'll drop regular HTTP connections that didn't request an upgrade just for the sake of getting rid of them, since they shouldn't interact.
Although you can try to make a dual webserver-WebSocket server I'd advise you to try that out later, as you need to make/change a lot of stuff yourself.

>To get an agar-like client, is there an easy way to do it? (As in make my own domain called sample.com and having sample.com/IP_ADDRESS work?

Get an Apache webserver running. Best option is to install either Xampp, nginx or Wamp. Just one is needed. I use Xampp myself.
Remember your webserver serving location. `~/www/` for Wamp, `~/htdocs/` for Xampp, I forgot for nginx. `~` is your tool's installation folder.
Clean that folder.
Download [Cigar](https://github.com/CigarProject/Cigar) and extract `/www` from the archive into that folder.
Open `/assets/main_out.js`. [Find line 181](https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L181). Hit enter and paste this code:
```js
var reg = /ip=([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}:[0-9]{1,5})/.exec(wHandle.location.search);
if (reg != null) wHandle.setserver(reg[1]);
```
Though not the best solution (it just tries connecting to the server when the site loads), it's the easiest one. To make it always connect to that server, you'll need a bit of PHP.

**Comment by LemonDoo** [comment]
Ah I see. I'm doing that right now, will get back with issues.

 Reading the documentation of Cigar, though, it says that Cigar is able to be run on a localhost?

**Comment by LemonDoo** [comment]
Also you stated: 

> A WebSocket server listens for HTTP (Hypertext Transfer Protocol) requests first.

If that is the case, why would it drop regular HTTP requests (that do not request an upgrade)?

So, to wrap it up, what we are doing is creating a separate Apache webserver to handle normal HTTP requests, and the Websockets listens for upgrade requests from the Apache webserver?

So it would be client---->webserver--->websockets??

Thanks for all your help!

**Comment by LemonDoo** [comment]
ok I got it to work, but I don't understand why I can go to my localhost/index.html and have it run my WebSocket on it even though Xampp doesn't run the Apache Server. Xampp does need to be open for the actual cells and everything to load, but it seems to not load Apache like I said?

Just a small thing, I'm just curious
