### ISSUE TITLE
Stability question

### ISSUE THREAD

**Issue by Gimmo** [Megabyte918/MultiOgar-Edited#86]
Why people need to restart MultiOgar servers? Often it happened every 3 hours.  It's bad system management or MultiOgar have some internal problems? What should I look for?

**Comment by Megabyte918** [comment]
@Gimmo Personally I've never experienced any issues with MultiOgar and leaving it running, i'm able to start up the server with 70 bots and 100 minions and leave it running overnight, and when I come back it would be exactly how I left it. But I assume that other people restart their servers because either people get too big, they've changed something within the code that requires a restart, or worst case scenario if their server gets botted while their not around, they can always count on the restart to reset everything.

**Comment by Gimmo** [comment]
Is there proven anti-bot measures or solutions? I wish to be able leave server intact for a few month.
I'm going to ban TOR and proxy connections to eliminate botters. Is there any inserver features to help this?
