### ISSUE TITLE
Is there a download so we can get Popsplit always success? No Fail?

### ISSUE THREAD

**Issue by NameYT** [Megabyte918/MultiOgar-Edited#9]
Hey i tried ur code but it did not work on the This project can u make 1 and send me a download link? it make my server dont work :(

**Comment by Megabyte918** [comment]
@NameYT For the last time, you did not follow the instructions correctly. You just pasted the code in random places. There is no download for perfect popsplits, you need to download the server and configure the settings to what you like for yourself. If your using this version of multiogar, all you need to do to increase the rate of popsplits working is to mess with the mult/second mult ratio's in virus.js. Nothing else. Don't add or do anything from my fix [here] (https://github.com/Barbosik/MultiOgar/issues/333#issuecomment-258656438) because most of it is already added or outdated in this version by now. If your using the original multiogar, make sure the code from Natsu's cells flying through other cells fix is pasted in the CORRECT place, before/after the specific lines of code. Don't just paste it on the same line number as that will break functionality. The green lines are what you need to add into GameServer.js, the red lines are what you need to remove. Don't just copy/paste everything you see. Then after that, continue on with the rest of the fix. After all of my fixes are added, the code is in the CORRECT place, and the server actually starts, you need to increase the splitMass variable to a higher number. Experiment with it, the higher the value of splitMass  is the more cells will pop out when hitting a virus, which means a higher chance popsplits will work.

**Comment by NameYT** [comment]
@Megabyte918 Cant you just give me the copy of Gameserver.js that change the server and other stuff to the server? That would be easier

**Comment by Fantasy-Agario** [comment]
No just because there's no point + if u really want to have 'Perfect Popsplits' u should do it yourself

**Comment by AlexandriteErikParacelsus** [comment]
@Fantasy-Agario good point
