### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by NuclearC** [Megabyte918/MultiOgar-Edited#927]
* Make Server update game logic 50 times per second (instead of 25):
I dont think it can affect game physics much but we need to try (it will still send updates at 25pps)
* Food Mass Grow: in official servers food is growing slow, MO-E spawns food at random Radius between 10-20
* Make better algorithm for getting safe spawn position: Sometimes i cant spawn even if there is free space in game server

I can make first 2 points myself, but i cant guarantee that my code would be readable, lol

**Comment by freaky767** [comment]
Make a PR about the 2 points and people will try to make it better I guess.

**Comment by MastaCoder** [comment]
The second option has been added to many other repos and it's been known to cause lag, I don't know if it can be done in Node.js without impacting performance eventually. Other 2 can be tried out :)

**Comment by pabloalber84** [comment]
The three option can't be possible.
Can be, but, if the random position function get modify and update to any place do not let the players, are going to get possible bugs or lags in the spawn, bugs, if the system dont search any safe position.... what happend?, and, if the map are small because gamemode, etc, where is going to indicate that spawn?.
One Better suggestion are:
Add a phantom fuction in the physics, to: if one player spawn, get invincible for 3 seconds, 3 seconds to split/get in safe position, but this too can get angry to player's, if get invincible, and other player are in front of him, can follow and if he split, get in and the player can made better random spawn.
Other better suggestion are:
Same invincible spawn with 3 seconds, but he can collapse with others players.

**Comment by Agarian** [comment]
I know this is a very old issue, but it is possible @pabloalber84, it's already happened

**Comment by Agarian** [comment]
It would appear that `unshift` seems to have no affect on double splits anymore. It's probably my server TBH lol. @Luka967 could you be of assistance? I'd ask you on Discord, but it appears you've left the server.

**Comment by B0RYS** [comment]
@NuclearC I've taken a look at the things you suggested and i have concluded that:
- Changing the update interval to the one you suggested will result in a severe performance drop (high drop in fps). Plus vanilla 
- Making the algorithm more lenient will frequently result in it being ineffective and most likely inefficient.

So unless you implement said features yourself in a way that doesn't affect the performance negatively, they are pretty impractical.

**Comment by NuclearC** [comment]
@B0RYS this was 2 years ago, come on

**Comment by B0RYS** [comment]
Someone had to do it, sorry @NuclearC.
