### ISSUE TITLE
Cannot Connect to the server

### ISSUE THREAD

**Issue by ExobyteZOfficial** [Megabyte918/MultiOgar-Edited#947]
Maybe agar update? idk
It say's Connecting ._.
Already Logout on FB/GMAIL
Still no luck?

**Comment by AlexHGaming** [comment]
Going to check and confirm.

**Comment by AlexHGaming** [comment]
Cannot reproduce
Proof: 
![image](https://user-images.githubusercontent.com/23644244/27547641-83a3e15c-5a8e-11e7-8e8b-cc5f50859ffc.png)
Please make sure nothing is blocking the connection.

**Comment by XxXN0SplittrXxX** [comment]
I also have this problem - Others can connect to my server fine, but I keep having the ''Connecting'' issue when I try to connect myself with the same link. Replacing the IP with localhost does not work either. I used to be able to run it with astr.io instead of agar.io, but it will not work anymore.

**Comment by AlexHGaming** [comment]
@ExobyteZOfficial @XxXN0SplittrXxX Well I could not reproduce. I even downloaded a clean, fresh server, I still am able to join a solo server fine.
@XxXN0SplittrXxX, you said `others can join my server fine`
Please make sure whatever you're hosting with, functions correctly.

**Comment by ExobyteZOfficial** [comment]
nvm it works :) @AlexHGaming It works in Incgoto Mode :D I close dis shitty ow
