### ISSUE TITLE
AI Splitrunning makes the game too easy

### ISSUE THREAD

**Issue by logicalatomical** [Megabyte918/MultiOgar-Edited#961]
Hello, I have been frustrated with the way that the bots try and splitrun with eachother. yes, they "try" to. They seem to be randomly splitting in and out of eachother and it makes the game too easy because they are no challenge to eat. So I have an idea to solve this for skilled players such as my self. You could add an option that allows the bots to team or not to team! This way they won't try to splitrun if I don't want them to! Thanks for looking into this! With regards! - Atomical

**Comment by pabloalber84** [comment]
This is duplicated, because in other issue say the same but differente, like "make the bots less stupids" :v is the same than you say.

**Comment by logicalatomical** [comment]
Not really, I am asking to make an option to disable splitrunning

**Comment by logicalatomical** [comment]
Because the bots don't actually splitrun with eachother.

**Comment by gyeyoqu** [comment]
@logicalatomical in ai/botPlayer.js , at the end find a comment that say 👍 


 // Splitting conditions

and delete the if/else, and  just leave what is inside the else

**Comment by ZfsrGhS953** [comment]
@gyeyoqu Did he ask how to disable bot splitting completely? No, he only wants to disable splitrunning.

**Comment by gyeyoqu** [comment]
@ZfsrGhS953  Bots have never done splitrun

**Comment by ZfsrGhS953** [comment]
@gyeyoqu He never said that the bots actually splitrun, they try to do it, but at some point they stop and allow players to eat them easily.

**Comment by logicalatomical** [comment]
ok now I have disabled it, thanks! but now the bots don't know when to split. Now I know how bad these ai are

**Comment by logicalatomical** [comment]
Lol now I think I know whats up with all of this splitrunning nonsense, the devs are too lazy to make bots smart enough to split. so they tried to make the bots team together, but then when they are big they no longer split unless they hit viruses. You guys have been busted. remove this post and I will make a youtube video that can get thousands of views

**Comment by Gigabyte918** [comment]
are you Atomical Tv YouTuber?

**Comment by fayizan** [comment]
@Gigabyte918 yes he is.... 

@logicalatomical Try the [Multiogar by Barbosik](https://github.com/Barbosik/MultiOgar) I think that bots AI is better than multiogar-edited

**Comment by gyeyoqu** [comment]
@logicalatomical 700 subs WOW THOUSAND OF VIEW !! WOWOWOOWOWW

**Comment by FantasyIsBae** [comment]
@logicalatomical 
>the devs are too lazy to make bots smart enough to split

Nope we have 213 more commits than the original MultiOgar , and a lot of hard work has been put towards this project , if you can't appreciate then just don't come here (Fuck off in other informal terms).
The bots are meant to be there to imitate the player's actions they have been improved over time.
As we are so so lazy , why the f**k don't you code the behavior of the bots yourself , because from my POV i don't think anyone cares too much. 

> but then when they are big they no longer split unless they hit viruses

Yet AGAIN why don't you code them yourself , please give it a go an make a pull request I'll be sure to merge it.

>You guys have been busted

Umm how , tell me have you uncovered something not known of?

>remove this post and I will make a youtube video that can get thousands of views

Firstly, it is not a post it is an issue.
Secondly, make a YT video I'm sure we would like some new visitors.
Thirdly, I couldn't care less if it got a thousand or a million views , all it does is goes to show how utterly ridiculous and ignorant you are.

**Comment by logicalatomical** [comment]
dont bs me

**Comment by FantasyIsBae** [comment]
@logicalatomical How am I?

**Comment by FantasyIsBae** [comment]
You can't bullshit a bullshitter

**Comment by chewydev** [comment]
@logicalatomical The devs aren't too lazy, they're doing this all for free. If they really wanted to they could take down the entire repository and not have any consequences. Also, to be fair, there are more things that need to be worked on, and we would be happy to help you support the repo! Why not learn javascript and start working on a new AI engine for the bots, whilst keeping the resource usage to a minimum, instead of bitching about the devs "being lazy".

**Comment by logicalatomical** [comment]
Nobody gives an absolute fuck weather they can or not. I am pissed because
every time someone mentions ai they back it up as if it was nothing at all,
I really just wish they would understand how good it would be for youtube
videos and how popular multiogar edited would get if people knew it was
like playing the old Agar.io

**Comment by chewydev** [comment]
@logicalatomical That's not really a valid reason, but i'll give you a free pass on that because you're "pissed". Anyways, I'm not sure why you're mentioned Agar.io, as it was developed by a completely different developer, and the backend of Agar.io and MultiOgar (Edited) are two completely different things. Also, Agar.io never had "smart" bots. Also, i've been playing Agar.io since the beta, and honestly i'd love to speak with the developer, as the concept of the game was a breakthrough in web gaming, known as the IO Game genre. If you want it so bad, out of pity i'll try and enhance the AI on my own fork, and make a merge request.

**Comment by logicalatomical** [comment]
A lot of peeps will want it, anyone who can add it in will be a complete
god!

**Comment by chewydev** [comment]
You don't have to be a dick about it then.

**Comment by logicalatomical** [comment]
I do when I see multiple others get turned down for the same thing. It just
really pisses me off when devs don't listen. I am sure we can all relate to
miniclip not adding more game modes

**Comment by Megabyte918** [comment]
@logicalatomical There is a reason why they get turned down, smarter AI leads to performance issues that vary depending on the smartness of the bots (you saw what happened with Ogar Unlimited). So increasing the smartness of bots while also maintaining a relatively good performance is a difficult task, especially for a server like this and a person like me who is not that good with AI. 
I've been working on this server, cleaning it up, fixing bugs, and optimizing it wherever I can to increase performance so I could make room for more fun stuff such as gamemodes and configs, and even smarter AI. And we do listen, there is just some things we choose not to add or put off until later, such as the smartness of the AI. 
If we took the time to add each and every request or feature to the server without taking time in between to fix the already-existing issues this project would end up like Ogar Unlimited did. 
I get that the current AI isn't the smartest out there, but the current AI is experimental, they were never intended to be smart enough to actually challenge a real player. They are mostly for testing purposes as the original Agar.io doesn't (and never had) smart bots, as @chewydev stated before. If I really wanted to I could just remove the bots all together.
There are more pressing matters and lots of bugs with this server that have yet to be fixed to deal with something like the "smartness of the AI". Just be grateful for what you have now and be patient until we fix the ACTUAL issues with the server.
If you really want the bots to be smarter, take @chewydev's advice and learn javascript. You could make your own smarter AI that could even challenge a real player!
