### ISSUE TITLE
Server protection against bots

### ISSUE THREAD

**Issue by TopoR1** [Megabyte918/MultiOgar-Edited#968]
Hello!

On my server they're in and the people who turn on their bots and, thus, not allowed to play other players. How to protect your server from bots? What and how\what files need to change something? 

For example, as in mgar.io and terr.io, if you go through Privat server, bots will work, and if in theirs, then the bots to work longer.

**Comment by plazo123** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/gameserver.ini#L71

**Comment by plazo123** [comment]
whats your server ?OR GAME ? sorry caps on

**Comment by TopoR1** [comment]
@plazo123 it's not that. Not helping, at all

**Comment by logicalatomical** [comment]
I think there is a scramble option

**Comment by logicalatomical** [comment]
look in gameserver.ini for the serverScrambleLevel

**Comment by pabloalber84** [comment]
The recommended is put:
`serverIpLimit = 2`
If you connect from agar.io direct:
`serverScrambleLevel = 2`
(If you don't connect from agar.io and use's other client, like protocol 5/6/etc, you can't put this because can have a problem with minimap or mapping).

**Comment by ZfsrGhS953** [comment]
@TopoR1 The bots are an unofficial part of the game made by the agar.io community to add more variety to the otherwise boring vanilla gameplay. To protect your server from going insane due to them, change the gameserver.ini options (the gameplay ones, not the scramble or IP limit) until the bots become balanced. If you can't do that, you don't have the skills that are necessary for hosting an agar.io server, go away and don't host a server.
